-- 004_expand_names.sql
-- Expand name database: ~150 girls + ~150 boys
-- Hybrid approach: top names have meanings, long tail without
-- Adds Dutch (NL) support throughout
-- Uses ON CONFLICT DO NOTHING so safe to re-run

-- Add unique constraint to prevent duplicates (safe if already exists)
ALTER TABLE names_db DROP CONSTRAINT IF EXISTS names_db_name_gender_unique;
ALTER TABLE names_db ADD CONSTRAINT names_db_name_gender_unique UNIQUE (name, gender);

ALTER TABLE name_popularity DROP CONSTRAINT IF EXISTS name_popularity_name_id_country_unique;
ALTER TABLE name_popularity ADD CONSTRAINT name_popularity_name_id_country_unique UNIQUE (name_id, country_code);

-- ─────────────────────────────────────────────────────────────
-- GIRL NAMES — with meanings (top popular across all countries)
-- ─────────────────────────────────────────────────────────────
INSERT INTO names_db (name, gender, meaning, origin) VALUES
  -- International / English
  ('Charlotte',  'girl', 'Free woman',                       'French'),
  ('Sophia',     'girl', 'Wisdom',                           'Greek'),
  ('Harper',     'girl', 'Harp player',                      'English'),
  ('Luna',       'girl', 'Moon',                             'Latin'),
  ('Lily',       'girl', 'Pure, flower of innocence',        'English'),
  ('Grace',      'girl', 'Elegance, divine favour',          'Latin'),
  ('Chloe',      'girl', 'Blooming, young green shoot',      'Greek'),
  ('Evelyn',     'girl', 'Wished-for child',                 'English'),
  ('Aria',       'girl', 'Air, song, melody',                'Italian'),
  ('Scarlett',   'girl', 'Bright red, fiery spirit',         'English'),
  ('Violet',     'girl', 'Purple flower, modesty',           'Latin'),
  ('Penelope',   'girl', 'Weaver, faithful wife',            'Greek'),
  ('Eleanor',    'girl', 'Bright, shining one',              'French'),
  ('Aurora',     'girl', 'Dawn, new beginnings',             'Latin'),
  ('Hazel',      'girl', 'Hazelnut tree, wisdom',            'English'),
  ('Stella',     'girl', 'Star',                             'Latin'),
  ('Nora',       'girl', 'Light, honour',                    'Irish'),
  ('Ellie',      'girl', 'Bright shining light',             'English'),
  ('Hannah',     'girl', 'Grace, favour',                    'Hebrew'),
  ('Abigail',    'girl', 'My father is joy',                 'Hebrew'),
  ('Emily',      'girl', 'Rival, eager',                     'Latin'),
  ('Layla',      'girl', 'Night beauty',                     'Arabic'),
  ('Madison',    'girl', 'Son of Matthew — now a girls name','English'),
  ('Victoria',   'girl', 'Victory',                          'Latin'),
  ('Aubrey',     'girl', 'Ruler of elves',                   'Germanic'),
  ('Zoey',       'girl', 'Life',                             'Greek'),
  ('Natalia',    'girl', 'Born on Christmas Day',            'Latin'),
  ('Claire',     'girl', 'Bright, clear, famous',            'French'),
  ('Bella',      'girl', 'Beautiful',                        'Italian'),
  ('Savannah',   'girl', 'Open plain, treeless landscape',   'Spanish'),
  ('Leah',       'girl', 'Weary, delicate',                  'Hebrew'),
  ('Audrey',     'girl', 'Noble strength',                   'English'),
  ('Riley',      'girl', 'Courageous, valiant',              'Irish'),
  ('Addison',    'girl', 'Son of Adam — now widely used',    'English'),
  ('Brooklyn',   'girl', 'Broken land — place name',        'English'),
  ('Skylar',     'girl', 'Scholar, eternal life',            'Dutch'),
  ('Avery',      'girl', 'Ruler of elves',                   'English'),
  ('Elizabeth',  'girl', 'My God is an oath',                'Hebrew'),
  ('Camila',     'girl', 'Attendant at a religious ceremony','Latin'),
  ('Piper',      'girl', 'Pipe player',                      'English'),
  -- British favourites
  ('Freya',      'girl', 'Noble woman, goddess of love',     'Norse'),
  ('Poppy',      'girl', 'Red flower, remembrance',          'English'),
  ('Isla',       'girl', 'Island',                           'Scottish'),
  ('Willow',     'girl', 'Graceful, slender tree',           'English'),
  ('Rosie',      'girl', 'Rose flower, beauty',              'English'),
  ('Daisy',      'girl', 'Day''s eye, cheerful',             'English'),
  ('Molly',      'girl', 'Sea of bitterness, star of the sea','Irish'),
  ('Phoebe',     'girl', 'Radiant, shining moon',            'Greek'),
  ('Imogen',     'girl', 'Maiden, innocent girl',            'Celtic'),
  ('Ruby',       'girl', 'Deep red gemstone, precious',      'Latin'),
  ('Harriet',    'girl', 'Home ruler',                       'Germanic'),
  ('Florence',   'girl', 'Flourishing, blooming',            'Latin'),
  ('Alice',      'girl', 'Noble, of noble kind',             'Germanic'),
  ('Rose',       'girl', 'Rose flower, love',                'Latin'),
  -- German favourites
  ('Lena',       'girl', 'Light, torch',                     'Greek'),
  ('Lea',        'girl', 'Weary, delicate',                  'Hebrew'),
  ('Leonie',     'girl', 'Lioness',                          'Latin'),
  ('Clara',      'girl', 'Bright, clear, famous',            'Latin'),
  ('Laura',      'girl', 'Laurel tree, victory',             'Latin'),
  ('Lara',       'girl', 'Cheerful, famous',                 'Latin'),
  ('Emilia',     'girl', 'Rival, industrious',               'Latin'),
  ('Maja',       'girl', 'Pearl, great one',                 'Slavic'),
  ('Johanna',    'girl', 'God is gracious',                  'Hebrew'),
  ('Luisa',      'girl', 'Famous warrior',                   'Germanic'),
  ('Katharina',  'girl', 'Pure',                             'Greek'),
  ('Hannah',     'girl', 'Grace, favour',                    'Hebrew'),
  ('Franziska',  'girl', 'Free woman, from France',          'Latin'),
  ('Lotte',      'girl', 'Free woman',                       'French'),
  ('Ida',        'girl', 'Industrious, hardworking',         'Germanic'),
  -- Czech favourites
  ('Eliška',     'girl', 'My God is an oath',                'Hebrew'),
  ('Lucie',      'girl', 'Light',                            'Latin'),
  ('Karolína',   'girl', 'Free woman',                       'Latin'),
  ('Veronika',   'girl', 'True image, she who brings victory','Greek'),
  ('Adéla',      'girl', 'Noble',                            'Germanic'),
  ('Petra',      'girl', 'Rock, stone',                      'Greek'),
  ('Barbora',    'girl', 'Stranger, foreign woman',          'Greek'),
  ('Kateřina',   'girl', 'Pure',                             'Greek'),
  ('Tereza',     'girl', 'To harvest',                       'Greek'),
  ('Kristýna',   'girl', 'Follower of Christ',               'Greek'),
  ('Markéta',    'girl', 'Pearl',                            'Greek'),
  ('Anežka',     'girl', 'Pure, holy',                       'Greek'),
  ('Lenka',      'girl', 'Light',                            'Greek'),
  ('Michaela',   'girl', 'Who is like God',                  'Hebrew'),
  -- Dutch favourites
  ('Femke',      'girl', 'Peace, girl of peace',             'Frisian'),
  ('Fleur',      'girl', 'Flower',                           'French'),
  ('Roos',       'girl', 'Rose',                             'Dutch'),
  ('Fenna',      'girl', 'Peace',                            'Frisian'),
  ('Noor',       'girl', 'Light',                            'Arabic'),
  ('Bo',         'girl', 'Living, precious',                 'Scandinavian'),
  ('Anouk',      'girl', 'Grace',                            'French'),
  ('Floor',      'girl', 'Flower, flourishing',              'Dutch'),
  ('Madelief',   'girl', 'Daisy flower',                     'Dutch'),
  ('Bente',      'girl', 'Blessed',                          'Scandinavian'),
  ('Sanne',      'girl', 'Lily',                             'Hebrew'),
  ('Merel',      'girl', 'Blackbird',                        'Dutch'),
  ('Linde',      'girl', 'Linden tree, gentle',              'Germanic'),
  ('Eline',      'girl', 'Light',                            'Greek'),
  ('Iris',       'girl', 'Rainbow, messenger of the gods',   'Greek'),
  ('Nina',       'girl', 'Grace, little girl',               'Spanish'),
  ('Julia',      'girl', 'Youthful, Jove''s child',          'Latin'),
  ('Sara',       'girl', 'Princess',                         'Hebrew'),
  ('Elisa',      'girl', 'My God is an oath',                'Hebrew'),
  ('Tess',       'girl', 'To harvest',                       'Greek'),
  ('Manon',      'girl', 'Bitter, beloved',                  'French'),
  ('Amber',      'girl', 'Precious jewel, golden',           'Arabic'),
  ('Lena',       'girl', 'Light, torch',                     'Greek'),
  ('Vera',       'girl', 'Faith, truth',                     'Latin'),
  -- Scandinavian crossovers popular in NL/DE
  ('Sigrid',     'girl', 'Beautiful victory',                'Norse'),
  ('Astrid',     'girl', 'Divinely beautiful',               'Norse'),
  ('Ingrid',     'girl', 'Beautiful, beloved',               'Norse'),
  ('Maja',       'girl', 'Pearl, great one',                 'Scandinavian'),
  ('Signe',      'girl', 'New victory',                      'Norse')
ON CONFLICT (name, gender) DO NOTHING;

-- Girl names without meanings (long tail — still searchable & rankable)
INSERT INTO names_db (name, gender, meaning, origin) VALUES
  ('Addisyn',  'girl', '', 'English'), ('Adeline', 'girl', '', 'French'),
  ('Aisha',    'girl', '', 'Arabic'),  ('Alexis',  'girl', '', 'Greek'),
  ('Alivia',   'girl', '', 'Latin'),   ('Alondra', 'girl', '', 'Spanish'),
  ('Alina',    'girl', '', 'Slavic'),  ('Aliya',   'girl', '', 'Arabic'),
  ('Annabelle','girl', '', 'French'),  ('Arabella','girl', '', 'Latin'),
  ('Ariana',   'girl', '', 'Italian'), ('Ashley',  'girl', '', 'English'),
  ('Athena',   'girl', '', 'Greek'),   ('Autumn',  'girl', '', 'English'),
  ('Ayla',     'girl', '', 'Turkish'), ('Beatrice','girl', '', 'Latin'),
  ('Bianca',   'girl', '', 'Italian'), ('Brianna', 'girl', '', 'Irish'),
  ('Caroline', 'girl', '', 'French'),  ('Catalina','girl', '', 'Spanish'),
  ('Cecilia',  'girl', '', 'Latin'),   ('Celeste', 'girl', '', 'Latin'),
  ('Diana',    'girl', '', 'Latin'),   ('Eliana',  'girl', '', 'Hebrew'),
  ('Elena',    'girl', '', 'Greek'),   ('Elsie',   'girl', '', 'Scottish'),
  ('Estelle',  'girl', '', 'French'),  ('Fatima',  'girl', '', 'Arabic'),
  ('Gabriella','girl', '', 'Hebrew'),  ('Georgia', 'girl', '', 'Greek'),
  ('Gracie',   'girl', '', 'English'), ('Hana',    'girl', '', 'Japanese'),
  ('Heidi',    'girl', '', 'Germanic'),('Helena',  'girl', '', 'Greek'),
  ('Jade',     'girl', '', 'Spanish'), ('Jamie',   'girl', '', 'Hebrew'),
  ('Jasmine',  'girl', '', 'Persian'), ('Josephine','girl','', 'Hebrew'),
  ('Kennedy',  'girl', '', 'Irish'),   ('Kira',    'girl', '', 'Persian'),
  ('Kylie',    'girl', '', 'Aboriginal'),('Lauren', 'girl','', 'English'),
  ('Lillian',  'girl', '', 'English'), ('Lola',    'girl', '', 'Spanish'),
  ('Lucy',     'girl', '', 'Latin'),   ('Lydia',   'girl', '', 'Greek'),
  ('Mackenzie','girl', '', 'Scottish'),('Maya',    'girl', '', 'Sanskrit'),
  ('Melanie',  'girl', '', 'Greek'),   ('Miranda', 'girl', '', 'Latin'),
  ('Naomi',    'girl', '', 'Hebrew'),  ('Nicole',  'girl', '', 'Greek'),
  ('Paisley',  'girl', '', 'Scottish'),('Paige',   'girl', '', 'English'),
  ('Paola',    'girl', '', 'Latin'),   ('Patricia','girl', '', 'Latin'),
  ('Peyton',   'girl', '', 'English'), ('Piper',   'girl', '', 'English'),
  ('Reagan',   'girl', '', 'Irish'),   ('Rebecca', 'girl', '', 'Hebrew'),
  ('Sadie',    'girl', '', 'Hebrew'),  ('Samantha','girl', '', 'Hebrew'),
  ('Sandra',   'girl', '', 'Greek'),   ('Seraphina','girl','', 'Hebrew'),
  ('Sienna',   'girl', '', 'Italian'), ('Taylor',  'girl', '', 'English'),
  ('Valentina','girl', '', 'Latin'),   ('Valeria', 'girl', '', 'Latin'),
  ('Vivienne', 'girl', '', 'French'),  ('Wren',    'girl', '', 'English'),
  ('Yasmine',  'girl', '', 'Arabic'),  ('Yara',    'girl', '', 'Arabic'),
  ('Zara',     'girl', '', 'Arabic'),  ('Zelda',   'girl', '', 'Germanic')
ON CONFLICT (name, gender) DO NOTHING;

-- ─────────────────────────────────────────────────────────────
-- BOY NAMES — with meanings
-- ─────────────────────────────────────────────────────────────
INSERT INTO names_db (name, gender, meaning, origin) VALUES
  -- International / English
  ('Liam',      'boy', 'Strong-willed warrior',          'Irish'),
  ('Noah',      'boy', 'Rest, comfort',                  'Hebrew'),
  ('Oliver',    'boy', 'Olive tree, symbol of peace',    'Latin'),
  ('Elijah',    'boy', 'My God is Yahweh',               'Hebrew'),
  ('James',     'boy', 'Supplanter',                     'Hebrew'),
  ('William',   'boy', 'Resolute protector',             'Germanic'),
  ('Benjamin',  'boy', 'Son of my right hand',           'Hebrew'),
  ('Lucas',     'boy', 'Light',                          'Greek'),
  ('Henry',     'boy', 'Ruler of the home',              'Germanic'),
  ('Alexander', 'boy', 'Defender of men',                'Greek'),
  ('Mason',     'boy', 'Stone worker',                   'English'),
  ('Ethan',     'boy', 'Strong, firm, enduring',         'Hebrew'),
  ('Daniel',    'boy', 'God is my judge',                'Hebrew'),
  ('Michael',   'boy', 'Who is like God',                'Hebrew'),
  ('Logan',     'boy', 'Little hollow',                  'Scottish'),
  ('Jackson',   'boy', 'Son of Jack',                    'English'),
  ('Sebastian', 'boy', 'Venerable, revered',             'Greek'),
  ('Aiden',     'boy', 'Little fire',                    'Irish'),
  ('Mateo',     'boy', 'Gift of God',                    'Spanish'),
  ('Jack',      'boy', 'God is gracious',                'English'),
  ('Owen',      'boy', 'Young warrior',                  'Welsh'),
  ('Theodore',  'boy', 'Gift of God',                    'Greek'),
  ('Julian',    'boy', 'Youthful, Jove''s child',        'Latin'),
  ('Grayson',   'boy', 'Son of the grey-haired one',     'English'),
  ('Leo',       'boy', 'Lion',                           'Latin'),
  ('Isaiah',    'boy', 'Salvation of the Lord',          'Hebrew'),
  ('Nathan',    'boy', 'He gave',                        'Hebrew'),
  ('Caleb',     'boy', 'Faithful, whole-hearted',        'Hebrew'),
  ('Luke',      'boy', 'Light-giving',                   'Greek'),
  ('Gabriel',   'boy', 'God is my strength',             'Hebrew'),
  ('Isaac',     'boy', 'He will laugh',                  'Hebrew'),
  ('Carter',    'boy', 'Cart driver, transporter',       'English'),
  ('Wyatt',     'boy', 'Brave in war',                   'English'),
  ('Dylan',     'boy', 'Son of the sea',                 'Welsh'),
  ('Ryan',      'boy', 'Little king',                    'Irish'),
  ('Lincoln',   'boy', 'Lake colony',                    'English'),
  ('Hudson',    'boy', 'Son of Hugh, mind and spirit',   'English'),
  ('Anthony',   'boy', 'Priceless, praiseworthy',        'Latin'),
  ('Dominic',   'boy', 'Belonging to the Lord',          'Latin'),
  ('Ezra',      'boy', 'Help, helper',                   'Hebrew'),
  -- British favourites
  ('George',    'boy', 'Farmer, earth worker',           'Greek'),
  ('Harry',     'boy', 'Army ruler',                     'Germanic'),
  ('Charlie',   'boy', 'Free man',                       'Germanic'),
  ('Freddie',   'boy', 'Peaceful ruler',                 'Germanic'),
  ('Oscar',     'boy', 'Divine spear, friend of deer',   'Norse'),
  ('Theo',      'boy', 'Gift of God',                    'Greek'),
  ('Alfie',     'boy', 'Elf counsel, wise',              'English'),
  ('Archie',    'boy', 'Truly brave',                    'Germanic'),
  ('Jasper',    'boy', 'Treasurer',                      'Persian'),
  ('Rupert',    'boy', 'Bright fame',                    'Germanic'),
  ('Arthur',    'boy', 'Bear king',                      'Celtic'),
  ('Edward',    'boy', 'Wealthy guardian',               'English'),
  ('Thomas',    'boy', 'Twin',                           'Aramaic'),
  ('Joseph',    'boy', 'God will add',                   'Hebrew'),
  -- German favourites
  ('Leon',      'boy', 'Lion',                           'Greek'),
  ('Luis',      'boy', 'Famous warrior',                 'Germanic'),
  ('Finn',      'boy', 'Fair, white',                    'Irish'),
  ('Paul',      'boy', 'Small, humble',                  'Latin'),
  ('Jonas',     'boy', 'Dove, gift of God',              'Hebrew'),
  ('Ben',       'boy', 'Son of the right hand',          'Hebrew'),
  ('Felix',     'boy', 'Happy, fortunate',               'Latin'),
  ('Elias',     'boy', 'My God is the Lord',             'Hebrew'),
  ('Luca',      'boy', 'Light',                          'Italian'),
  ('Tim',       'boy', 'Honouring God',                  'Greek'),
  ('Nico',      'boy', 'Victory of the people',          'Greek'),
  ('Max',       'boy', 'Greatest',                       'Latin'),
  ('Moritz',    'boy', 'Dark-skinned, Moorish',          'Latin'),
  ('Fabian',    'boy', 'Bean grower',                    'Latin'),
  ('Tobias',    'boy', 'God is good',                    'Hebrew'),
  ('Philipp',   'boy', 'Lover of horses',                'Greek'),
  ('Markus',    'boy', 'Of Mars, warlike',               'Latin'),
  ('Stefan',    'boy', 'Crown, wreath',                  'Greek'),
  ('Simon',     'boy', 'He who listens',                 'Hebrew'),
  ('Johannes',  'boy', 'God is gracious',                'Hebrew'),
  -- Czech favourites
  ('Jakub',     'boy', 'Supplanter, may God protect',    'Hebrew'),
  ('Jan',       'boy', 'God is gracious',                'Hebrew'),
  ('Lukáš',     'boy', 'Light, illumination',            'Greek'),
  ('Matěj',     'boy', 'Gift of God',                    'Hebrew'),
  ('Ondřej',    'boy', 'Manly, brave',                   'Greek'),
  ('Marek',     'boy', 'Of Mars, warlike',               'Latin'),
  ('Tomáš',     'boy', 'Twin',                           'Aramaic'),
  ('Petr',      'boy', 'Rock, stone',                    'Greek'),
  ('Jiří',      'boy', 'Farmer, earth worker',           'Greek'),
  ('Martin',    'boy', 'Of Mars, warlike',               'Latin'),
  ('Vojtěch',   'boy', 'Joyful warrior',                 'Slavic'),
  ('Václav',    'boy', 'More glory',                     'Slavic'),
  ('Michal',    'boy', 'Who is like God',                'Hebrew'),
  ('Radek',     'boy', 'Happy, glad',                    'Slavic'),
  ('Zdeněk',    'boy', 'Follower of Saint Denis',        'Slavic'),
  -- Dutch favourites
  ('Sem',       'boy', 'Name of God, renown',            'Hebrew'),
  ('Daan',      'boy', 'God is my judge',                'Hebrew'),
  ('Lars',      'boy', 'Crowned with laurel',            'Scandinavian'),
  ('Bram',      'boy', 'Father of many nations',         'Hebrew'),
  ('Thijs',     'boy', 'Gift of God',                    'Dutch'),
  ('Luuk',      'boy', 'Light',                          'Greek'),
  ('Floris',    'boy', 'Flourishing, blooming',          'Latin'),
  ('Stijn',     'boy', 'Stone',                          'Dutch'),
  ('Joris',     'boy', 'Farmer, earth worker',           'Greek'),
  ('Sven',      'boy', 'Young man, boy',                 'Scandinavian'),
  ('Ruben',     'boy', 'Behold, a son',                  'Hebrew'),
  ('Niels',     'boy', 'Victory of the people',          'Greek'),
  ('Cas',       'boy', 'Treasurer',                      'Persian'),
  ('Wout',      'boy', 'Forest ruler',                   'Germanic'),
  ('Milan',     'boy', 'Kind, gracious',                 'Slavic'),
  ('Robin',     'boy', 'Fame-bright',                    'Germanic'),
  ('Jesse',     'boy', 'Gift, God exists',               'Hebrew'),
  ('Rick',      'boy', 'Powerful ruler',                 'Germanic'),
  ('Tom',       'boy', 'Twin',                           'Aramaic'),
  ('Sam',       'boy', 'Told by God',                    'Hebrew'),
  ('Adam',      'boy', 'Son of the red earth',           'Hebrew'),
  ('David',     'boy', 'Beloved',                        'Hebrew'),
  -- Scandinavian crossovers
  ('Erik',      'boy', 'Eternal ruler',                  'Norse'),
  ('Magnus',    'boy', 'Great, mighty',                  'Latin'),
  ('Axel',      'boy', 'Father of peace',                'Hebrew'),
  ('Leif',      'boy', 'Heir, descendant',               'Norse'),
  ('Björn',     'boy', 'Bear',                           'Norse')
ON CONFLICT (name, gender) DO NOTHING;

-- Boy names without meanings (long tail)
INSERT INTO names_db (name, gender, meaning, origin) VALUES
  ('Aaron',    'boy', '', 'Hebrew'),  ('Adrian',  'boy', '', 'Latin'),
  ('Alan',     'boy', '', 'Celtic'),  ('Alberto', 'boy', '', 'Germanic'),
  ('Alejandro','boy', '', 'Spanish'), ('Andres',  'boy', '', 'Greek'),
  ('Angel',    'boy', '', 'Greek'),   ('Austin',  'boy', '', 'Latin'),
  ('Blake',    'boy', '', 'English'), ('Brady',   'boy', '', 'Irish'),
  ('Brandon',  'boy', '', 'English'), ('Brendan', 'boy', '', 'Irish'),
  ('Brian',    'boy', '', 'Irish'),   ('Bryan',   'boy', '', 'Irish'),
  ('Cameron',  'boy', '', 'Scottish'),('Christian','boy','', 'Greek'),
  ('Christopher','boy','','Greek'),   ('Cole',    'boy', '', 'English'),
  ('Colin',    'boy', '', 'Irish'),   ('Connor',  'boy', '', 'Irish'),
  ('Cooper',   'boy', '', 'English'), ('Damian',  'boy', '', 'Greek'),
  ('Declan',   'boy', '', 'Irish'),   ('Diego',   'boy', '', 'Spanish'),
  ('Drew',     'boy', '', 'Greek'),   ('Elliot',  'boy', '', 'Hebrew'),
  ('Emmett',   'boy', '', 'English'), ('Evan',    'boy', '', 'Welsh'),
  ('Everett',  'boy', '', 'English'), ('Ezekiel', 'boy', '', 'Hebrew'),
  ('Finnegan', 'boy', '', 'Irish'),   ('Francisco','boy','', 'Latin'),
  ('Garrett',  'boy', '', 'Germanic'),('Grant',   'boy', '', 'English'),
  ('Greyson',  'boy', '', 'English'), ('Griffin', 'boy', '', 'Welsh'),
  ('Hayden',   'boy', '', 'English'), ('Ian',     'boy', '', 'Scottish'),
  ('Ivan',     'boy', '', 'Slavic'),  ('Jace',    'boy', '', 'Hebrew'),
  ('Jake',     'boy', '', 'Hebrew'),  ('Jonah',   'boy', '', 'Hebrew'),
  ('Jordan',   'boy', '', 'Hebrew'),  ('Jose',    'boy', '', 'Hebrew'),
  ('Joshua',   'boy', '', 'Hebrew'),  ('Justin',  'boy', '', 'Latin'),
  ('Kevin',    'boy', '', 'Irish'),   ('Kyle',    'boy', '', 'Scottish'),
  ('Lance',    'boy', '', 'Germanic'),('Landon',  'boy', '', 'English'),
  ('Lorenzo',  'boy', '', 'Latin'),   ('Marcus',  'boy', '', 'Latin'),
  ('Matthew',  'boy', '', 'Hebrew'),  ('Miles',   'boy', '', 'Latin'),
  ('Mitchell', 'boy', '', 'Hebrew'),  ('Nicolas', 'boy', '', 'Greek'),
  ('Nolan',    'boy', '', 'Irish'),   ('Omar',    'boy', '', 'Arabic'),
  ('Parker',   'boy', '', 'English'), ('Patrick', 'boy', '', 'Latin'),
  ('Preston',  'boy', '', 'English'), ('Reid',    'boy', '', 'Scottish'),
  ('Rhys',     'boy', '', 'Welsh'),   ('Richard', 'boy', '', 'Germanic'),
  ('Robert',   'boy', '', 'Germanic'),('Roman',   'boy', '', 'Latin'),
  ('Rowan',    'boy', '', 'Irish'),   ('Russell', 'boy', '', 'French'),
  ('Scott',    'boy', '', 'English'), ('Tristan', 'boy', '', 'Celtic'),
  ('Tucker',   'boy', '', 'English'), ('Tyler',   'boy', '', 'English'),
  ('Victor',   'boy', '', 'Latin'),   ('Vincent', 'boy', '', 'Latin'),
  ('Wesley',   'boy', '', 'English'), ('Zachary', 'boy', '', 'Hebrew')
ON CONFLICT (name, gender) DO NOTHING;

-- ─────────────────────────────────────────────────────────────
-- POPULARITY DATA  (NL + fill-in for new names)
-- ─────────────────────────────────────────────────────────────

-- Girls popularity
WITH n AS (SELECT id, name FROM names_db WHERE gender = 'girl')
INSERT INTO name_popularity (name_id, country_code, popularity_rank, year)
SELECT n.id, p.country_code, p.rank, 2024
FROM n JOIN (VALUES
  -- NL (Netherlands) — girls
  ('Emma',       'NL', 1),  ('Mia',       'NL', 3),  ('Sofia',     'NL', 5),
  ('Julia',      'NL', 4),  ('Olivia',    'NL', 6),  ('Lotte',     'NL', 7),
  ('Sara',       'NL', 8),  ('Anna',      'NL', 9),  ('Noor',      'NL', 2),
  ('Fleur',      'NL', 10), ('Femke',     'NL', 11), ('Roos',      'NL', 13),
  ('Floor',      'NL', 14), ('Anouk',     'NL', 15), ('Fenna',     'NL', 16),
  ('Luna',       'NL', 17), ('Bo',        'NL', 18), ('Lena',      'NL', 19),
  ('Nina',       'NL', 20), ('Iris',      'NL', 21), ('Elisa',     'NL', 22),
  ('Tess',       'NL', 23), ('Amber',     'NL', 24), ('Bente',     'NL', 25),
  ('Sanne',      'NL', 26), ('Merel',     'NL', 27), ('Linde',     'NL', 28),
  ('Eline',      'NL', 29), ('Madelief',  'NL', 30), ('Hannah',    'NL', 31),
  ('Ella',       'NL', 32), ('Charlotte', 'NL', 33), ('Lily',      'NL', 34),
  ('Manon',      'NL', 35), ('Vera',      'NL', 36), ('Skylar',    'NL', 12),
  -- GB (United Kingdom) — new/missing
  ('Charlotte',  'GB', 4),  ('Harper',    'GB', 7),  ('Lily',      'GB', 9),
  ('Grace',      'GB', 11), ('Chloe',     'GB', 13), ('Evelyn',    'GB', 14),
  ('Violet',     'GB', 16), ('Eleanor',   'GB', 17), ('Hazel',     'GB', 18),
  ('Stella',     'GB', 19), ('Nora',      'GB', 20), ('Emily',     'GB', 5),
  ('Ruby',       'GB', 6),  ('Poppy',     'GB', 8),  ('Daisy',     'GB', 10),
  ('Alice',      'GB', 21), ('Rose',      'GB', 22), ('Florence',  'GB', 23),
  ('Harriet',    'GB', 24), ('Phoebe',    'GB', 25), ('Imogen',    'GB', 26),
  ('Freya',      'GB', 27), ('Isla',      'GB', 28), ('Willow',    'GB', 29),
  ('Rosie',      'GB', 30), ('Molly',     'GB', 31), ('Luna',      'GB', 32),
  -- US — new/missing
  ('Charlotte',  'US', 3),  ('Harper',    'US', 9),  ('Evelyn',    'US', 6),
  ('Abigail',    'US', 11), ('Emily',     'US', 12), ('Ella',      'US', 13),
  ('Elizabeth',  'US', 14), ('Camila',    'US', 15), ('Avery',     'US', 16),
  ('Luna',       'US', 17), ('Aria',      'US', 18), ('Scarlett',  'US', 19),
  ('Penelope',   'US', 20), ('Layla',     'US', 21), ('Chloe',     'US', 22),
  ('Victoria',   'US', 23), ('Madison',   'US', 24), ('Eleanor',   'US', 26),
  ('Grace',      'US', 27), ('Nora',      'US', 28), ('Riley',     'US', 29),
  ('Zoey',       'US', 30), ('Hannah',    'US', 31), ('Lily',      'US', 32),
  ('Aubrey',     'US', 33), ('Ellie',     'US', 34), ('Stella',    'US', 35),
  ('Violet',     'US', 36), ('Aurora',    'US', 37), ('Savannah',  'US', 38),
  ('Audrey',     'US', 39), ('Bella',     'US', 40), ('Claire',    'US', 41),
  ('Skylar',     'US', 42), ('Leah',      'US', 43), ('Hazel',     'US', 44),
  -- DE (Germany) — new/missing
  ('Emma',       'DE', 1),  ('Mia',       'DE', 2),  ('Lena',      'DE', 3),
  ('Sofia',      'DE', 4),  ('Lea',       'DE', 5),  ('Leonie',    'DE', 6),
  ('Hannah',     'DE', 7),  ('Lara',      'DE', 8),  ('Anna',      'DE', 9),
  ('Laura',      'DE', 10), ('Emilia',    'DE', 11), ('Maja',      'DE', 12),
  ('Johanna',    'DE', 13), ('Clara',     'DE', 14), ('Charlotte', 'DE', 15),
  ('Luisa',      'DE', 16), ('Lotte',     'DE', 17), ('Marie',     'DE', 18),
  ('Lina',       'DE', 19), ('Nora',      'DE', 20), ('Olivia',    'DE', 21),
  ('Katharina',  'DE', 22), ('Franziska', 'DE', 23), ('Ida',       'DE', 24),
  -- CZ (Czech Republic) — new/missing
  ('Mia',        'CZ', 1),  ('Sofia',     'CZ', 2),  ('Emma',      'CZ', 3),
  ('Lucie',      'CZ', 4),  ('Anna',      'CZ', 5),  ('Tereza',    'CZ', 6),
  ('Marie',      'CZ', 7),  ('Olivia',    'CZ', 8),  ('Eva',       'CZ', 9),
  ('Natalie',    'CZ', 10), ('Eliška',    'CZ', 11), ('Karolína',  'CZ', 12),
  ('Veronika',   'CZ', 13), ('Adéla',     'CZ', 14), ('Petra',     'CZ', 15),
  ('Barbora',    'CZ', 16), ('Kateřina',  'CZ', 17), ('Kristýna',  'CZ', 18),
  ('Markéta',    'CZ', 19), ('Anežka',    'CZ', 20), ('Lenka',     'CZ', 21),
  ('Michaela',   'CZ', 22), ('Ella',      'CZ', 23), ('Zoe',       'CZ', 24)
) AS p(name, country_code, rank) ON n.name = p.name
ON CONFLICT (name_id, country_code) DO NOTHING;

-- Boys popularity
WITH n AS (SELECT id, name FROM names_db WHERE gender = 'boy')
INSERT INTO name_popularity (name_id, country_code, popularity_rank, year)
SELECT n.id, p.country_code, p.rank, 2024
FROM n JOIN (VALUES
  -- NL (Netherlands) — boys
  ('Sem',       'NL', 1),  ('Noah',      'NL', 2),  ('Daan',      'NL', 3),
  ('Lars',      'NL', 4),  ('Liam',      'NL', 5),  ('Bram',      'NL', 6),
  ('Finn',      'NL', 7),  ('Thijs',     'NL', 8),  ('Jesse',     'NL', 9),
  ('Luuk',      'NL', 10), ('Floris',    'NL', 11), ('Stijn',     'NL', 12),
  ('Joris',     'NL', 13), ('Sven',      'NL', 14), ('Ruben',     'NL', 15),
  ('Julian',    'NL', 16), ('Thomas',    'NL', 17), ('Milan',     'NL', 18),
  ('Robin',     'NL', 19), ('Rick',      'NL', 20), ('Niels',     'NL', 21),
  ('Tom',       'NL', 22), ('Sam',       'NL', 23), ('Cas',       'NL', 24),
  ('Wout',      'NL', 25), ('Oliver',    'NL', 26), ('Jasper',    'NL', 27),
  ('Tim',       'NL', 28), ('Max',       'NL', 29), ('Lucas',     'NL', 30),
  ('Felix',     'NL', 31), ('Simon',     'NL', 32), ('Leon',      'NL', 33),
  ('Luca',      'NL', 34), ('David',     'NL', 35), ('Adam',      'NL', 36),
  -- GB — new/missing
  ('Oliver',    'GB', 1),  ('George',    'GB', 2),  ('Liam',      'GB', 3),
  ('Harry',     'GB', 4),  ('Henry',     'GB', 5),  ('Charlie',   'GB', 6),
  ('Freddie',   'GB', 7),  ('Lucas',     'GB', 8),  ('Oscar',     'GB', 9),
  ('Jack',      'GB', 10), ('Theo',      'GB', 11), ('Alfie',     'GB', 12),
  ('Archie',    'GB', 13), ('Jasper',    'GB', 14), ('Arthur',    'GB', 15),
  ('Edward',    'GB', 16), ('Thomas',    'GB', 17), ('Joseph',    'GB', 18),
  ('Rupert',    'GB', 19), ('Sebastian', 'GB', 20), ('Leo',       'GB', 21),
  ('Felix',     'GB', 22), ('Finn',      'GB', 23), ('Dylan',     'GB', 24),
  -- US — new/missing
  ('William',   'US', 4),  ('Benjamin',  'US', 6),  ('Mason',     'US', 8),
  ('Ethan',     'US', 11), ('Daniel',    'US', 12), ('Michael',   'US', 13),
  ('Logan',     'US', 14), ('Jackson',   'US', 15), ('Sebastian', 'US', 16),
  ('Aiden',     'US', 17), ('Mateo',     'US', 18), ('Jack',      'US', 19),
  ('Owen',      'US', 20), ('Theodore',  'US', 21), ('Julian',    'US', 22),
  ('Grayson',   'US', 23), ('Leo',       'US', 24), ('Isaiah',    'US', 25),
  ('Nathan',    'US', 26), ('Caleb',     'US', 27), ('Luke',      'US', 28),
  ('Gabriel',   'US', 29), ('Isaac',     'US', 30), ('Carter',    'US', 31),
  ('Wyatt',     'US', 32), ('Dylan',     'US', 33), ('Ryan',      'US', 34),
  ('Lincoln',   'US', 35), ('Hudson',    'US', 36), ('Anthony',   'US', 37),
  ('Dominic',   'US', 38), ('Ezra',      'US', 39), ('Alexander', 'US', 40),
  -- DE — new/missing
  ('Oliver',    'DE', 1),  ('Lucas',     'DE', 2),  ('Noah',      'DE', 3),
  ('Leon',      'DE', 4),  ('Luis',      'DE', 5),  ('Finn',      'DE', 6),
  ('Paul',      'DE', 7),  ('Jonas',     'DE', 8),  ('Ben',       'DE', 9),
  ('Felix',     'DE', 10), ('Noah',      'DE', 3),  ('Elias',     'DE', 11),
  ('Luca',      'DE', 12), ('Tim',       'DE', 13), ('Jan',       'DE', 14),
  ('Nico',      'DE', 15), ('Max',       'DE', 16), ('Moritz',    'DE', 17),
  ('Fabian',    'DE', 18), ('Tobias',    'DE', 19), ('Philipp',   'DE', 20),
  ('Markus',    'DE', 21), ('Stefan',    'DE', 22), ('Simon',     'DE', 23),
  ('Johannes',  'DE', 24), ('Henry',     'DE', 25), ('Liam',      'DE', 26),
  -- CZ — new/missing
  ('Jan',       'CZ', 1),  ('Jakub',     'CZ', 2),  ('Lukáš',     'CZ', 3),
  ('Matěj',     'CZ', 4),  ('Adam',      'CZ', 5),  ('David',     'CZ', 6),
  ('Martin',    'CZ', 7),  ('Tomáš',     'CZ', 8),  ('Ondřej',    'CZ', 9),
  ('Marek',     'CZ', 10), ('Petr',      'CZ', 11), ('Jiří',      'CZ', 12),
  ('Vojtěch',   'CZ', 13), ('Václav',    'CZ', 14), ('Michal',    'CZ', 15),
  ('Radek',     'CZ', 16), ('Zdeněk',    'CZ', 17), ('Milan',     'CZ', 18),
  ('Liam',      'CZ', 19), ('Noah',      'CZ', 20), ('Lucas',     'CZ', 21),
  ('Oliver',    'CZ', 22), ('Finn',      'CZ', 23), ('Leo',       'CZ', 24)
) AS p(name, country_code, rank) ON n.name = p.name
ON CONFLICT (name_id, country_code) DO NOTHING;
