-- 005_more_cz_nl_names.sql
-- Huge expansion of Czech and Dutch names — popular, uncommon, and traditional
-- Safe to re-run (ON CONFLICT DO NOTHING throughout)

-- ─────────────────────────────────────────────────────────────
-- CZECH GIRL NAMES
-- ─────────────────────────────────────────────────────────────
INSERT INTO names_db (name, gender, meaning, origin) VALUES
  -- Modern & popular
  ('Klára',      'girl', 'Bright, clear, famous',             'Latin'),
  ('Nikola',     'girl', 'Victory of the people',             'Greek'),
  ('Simona',     'girl', 'God has heard',                     'Hebrew'),
  ('Dominika',   'girl', 'Belonging to the Lord',             'Latin'),
  ('Jana',       'girl', 'God is gracious',                   'Hebrew'),
  ('Martina',    'girl', 'Of Mars, warlike',                  'Latin'),
  ('Alžběta',    'girl', 'My God is an oath',                 'Hebrew'),
  ('Zuzana',     'girl', 'Lily, graceful',                    'Hebrew'),
  ('Amálie',     'girl', 'Work, effort, industrious',         'Germanic'),
  ('Rozálie',    'girl', 'Rose, beautiful flower',            'Latin'),
  ('Žofie',      'girl', 'Wisdom',                            'Greek'),
  ('Viktorie',   'girl', 'Victory',                           'Latin'),
  ('Julie',      'girl', 'Youthful, Jove''s child',           'Latin'),
  ('Nela',       'girl', 'Bright, shining one',               'Greek'),
  ('Ema',        'girl', 'Whole, universal',                  'Germanic'),
  ('Sára',       'girl', 'Princess',                          'Hebrew'),
  ('Linda',      'girl', 'Pretty, soft, gentle',              'Spanish'),
  ('Pavlína',    'girl', 'Small, humble',                     'Latin'),
  ('Monika',     'girl', 'Advisor, solitary',                 'Latin'),
  ('Denisa',     'girl', 'Follower of Dionysus',              'Greek'),
  ('Kamila',     'girl', 'Attendant at a ceremony',           'Latin'),
  ('Šárka',      'girl', 'Mythological Czech heroine',        'Slavic'),
  ('Radka',      'girl', 'Happy, glad',                       'Slavic'),
  ('Alena',      'girl', 'Bright, shining light',             'Slavic'),
  ('Ivana',      'girl', 'God is gracious',                   'Slavic'),
  ('Johana',     'girl', 'God is gracious',                   'Hebrew'),
  ('Marie',      'girl', 'Beloved, wished-for child',         'Hebrew'),
  ('Eva',        'girl', 'Life, living',                      'Hebrew'),
  ('Hana',       'girl', 'Grace, favour',                     'Hebrew'),
  ('Natálie',    'girl', 'Born on Christmas Day',             'Latin'),
  ('Zoe',        'girl', 'Life',                              'Greek'),
  ('Mia',        'girl', 'Mine, beloved',                     'Scandinavian'),
  ('Daniela',    'girl', 'God is my judge',                   'Hebrew'),
  ('Gabriela',   'girl', 'God is my strength',                'Hebrew'),
  ('Romana',     'girl', 'From Rome, Roman',                  'Latin'),
  ('Isabela',    'girl', 'My God is an oath',                 'Hebrew'),
  ('Sylva',      'girl', 'From the forest',                   'Latin'),
  ('Agáta',      'girl', 'Good, honourable',                  'Greek'),
  ('Cecílie',    'girl', 'Blind, sixth',                      'Latin'),
  ('Edita',      'girl', 'Rich gift, wealth',                 'Germanic'),
  ('Iva',        'girl', 'Yew tree',                          'Slavic'),
  ('Iveta',      'girl', 'God is gracious',                   'Slavic'),
  ('Soňa',       'girl', 'Wisdom',                            'Greek'),
  ('Taťána',     'girl', 'Fairy queen',                       'Slavic'),
  ('Yveta',      'girl', 'Yew tree',                          'French'),
  ('Jitka',      'girl', 'Jewish woman',                      'Hebrew'),
  ('Jarmila',    'girl', 'Spring grace',                      'Slavic'),
  ('Darina',     'girl', 'Gift',                              'Slavic'),
  ('Blanka',     'girl', 'White, pure',                       'Germanic'),
  ('Renata',     'girl', 'Reborn',                            'Latin'),
  ('Irena',      'girl', 'Peace',                             'Greek'),
  ('Dagmar',     'girl', 'Bright day',                        'Germanic'),
  ('Vanda',      'girl', 'From the Vandal tribe',             'Germanic'),
  ('Bohumila',   'girl', 'Dear to God',                       'Slavic'),
  ('Mirka',      'girl', 'Peace and glory',                   'Slavic'),
  ('Vanessa',    'girl', 'Butterfly',                         'Greek'),
  ('Dana',       'girl', 'God is my judge',                   'Hebrew'),
  ('Věra',       'girl', 'Faith, truth',                      'Slavic'),
  -- Traditional & historic Czech
  ('Ludmila',    'girl', 'People''s grace',                   'Slavic'),
  ('Božena',     'girl', 'Divine, God''s gift',               'Slavic'),
  ('Vlasta',     'girl', 'Rule, power, homeland',             'Slavic'),
  ('Libuše',     'girl', 'Dear, beloved',                     'Slavic'),
  ('Milena',     'girl', 'Gracious, pleasant',                'Slavic'),
  ('Milada',     'girl', 'Gracious, young',                   'Slavic'),
  ('Jaroslava',  'girl', 'Bright spring glory',               'Slavic'),
  ('Stanislava', 'girl', 'Glorious government',               'Slavic'),
  ('Vladislava', 'girl', 'Glorious ruler',                    'Slavic'),
  ('Drahomíra',  'girl', 'Dear peace',                        'Slavic'),
  ('Lada',       'girl', 'Goddess of love and spring',        'Slavic'),
  ('Doubravka',  'girl', 'Oak grove',                         'Slavic'),
  ('Jaromíra',   'girl', 'Spring peace',                      'Slavic'),
  ('Vlastimila', 'girl', 'Gracious ruler',                    'Slavic'),
  ('Slavomíra',  'girl', 'Glory and peace',                   'Slavic'),
  ('Zdena',      'girl', 'Follower of Saint Denis',           'Slavic'),
  ('Zdeňka',     'girl', 'Follower of Saint Denis',           'Slavic'),
  ('Naděje',     'girl', 'Hope',                              'Slavic'),
  ('Růžena',     'girl', 'Rose',                              'Czech'),
  ('Brigita',    'girl', 'Strength, exalted one',             'Celtic'),
  ('Drahuše',    'girl', 'Dear one, precious',                'Slavic'),
  ('Doubravka',  'girl', 'Oak grove, forest',                 'Slavic'),
  ('Kvetoslava', 'girl', 'Flowering glory',                   'Slavic'),
  ('Miluše',     'girl', 'Gracious, dear',                    'Slavic'),
  ('Marta',      'girl', 'Lady, mistress',                    'Aramaic'),
  ('Olga',       'girl', 'Holy, blessed',                     'Norse'),
  ('Pavla',      'girl', 'Small, humble',                     'Latin'),
  ('Žaneta',     'girl', 'God is gracious',                   'Hebrew'),
  ('Magdalena',  'girl', 'From Magdala, tower',               'Hebrew'),
  ('Antonie',    'girl', 'Priceless, praiseworthy',           'Latin'),
  ('Jindřiška',  'girl', 'Ruler of the home',                 'Germanic'),
  ('Albína',     'girl', 'White, fair',                       'Latin'),
  ('Anděla',     'girl', 'Angel, messenger',                  'Greek'),
  ('Hedvika',    'girl', 'Battle, strife',                    'Germanic'),
  ('Markéta',    'girl', 'Pearl',                             'Greek'),
  ('Zita',       'girl', 'Little hope, seeker',               'Italian'),
  ('Běla',       'girl', 'White, fair',                       'Slavic'),
  ('Slavka',     'girl', 'Glory',                             'Slavic'),
  ('Radmila',    'girl', 'Happy grace',                       'Slavic'),
  ('Dobromila',  'girl', 'Good and gracious',                 'Slavic'),
  ('Bronislava', 'girl', 'Armoured glory',                    'Slavic'),
  ('Miroslava',  'girl', 'Peace and glory',                   'Slavic')
ON CONFLICT (name, gender) DO NOTHING;

-- ─────────────────────────────────────────────────────────────
-- CZECH BOY NAMES
-- ─────────────────────────────────────────────────────────────
INSERT INTO names_db (name, gender, meaning, origin) VALUES
  -- Modern & popular
  ('Filip',      'boy', 'Lover of horses',                'Greek'),
  ('Šimon',      'boy', 'God has heard',                  'Hebrew'),
  ('Dominik',    'boy', 'Belonging to the Lord',          'Latin'),
  ('Patrik',     'boy', 'Noble, patrician',               'Latin'),
  ('Pavel',      'boy', 'Small, humble',                  'Latin'),
  ('Josef',      'boy', 'God will add',                   'Hebrew'),
  ('Karel',      'boy', 'Free man',                       'Germanic'),
  ('František',  'boy', 'Free man, from France',          'Latin'),
  ('Miroslav',   'boy', 'Peace and glory',                'Slavic'),
  ('Antonín',    'boy', 'Priceless, praiseworthy',        'Latin'),
  ('Stanislav',  'boy', 'To become glorious',             'Slavic'),
  ('Vladimír',   'boy', 'Great ruler',                    'Slavic'),
  ('Matyáš',     'boy', 'Gift of God',                    'Hebrew'),
  ('Štěpán',     'boy', 'Crown, wreath',                  'Greek'),
  ('Kristián',   'boy', 'Follower of Christ',             'Greek'),
  ('Kryštof',    'boy', 'Bearer of Christ',               'Greek'),
  ('Jonáš',      'boy', 'Dove, gift of God',              'Hebrew'),
  ('Sebastián',  'boy', 'Venerable, revered',             'Greek'),
  ('Tobiáš',     'boy', 'God is good',                    'Hebrew'),
  ('Vít',        'boy', 'Life, lively',                   'Latin'),
  ('Ladislav',   'boy', 'Famous ruler',                   'Slavic'),
  ('Jaroslav',   'boy', 'Bright spring glory',            'Slavic'),
  ('Oldřich',    'boy', 'Wealth and power',               'Germanic'),
  ('Bedřich',    'boy', 'Peaceful ruler',                 'Germanic'),
  ('Radoslav',   'boy', 'Happy glory',                    'Slavic'),
  ('Bohumil',    'boy', 'Dear to God',                    'Slavic'),
  ('Bohdan',     'boy', 'Gift of God',                    'Slavic'),
  ('Samuel',     'boy', 'Told by God',                    'Hebrew'),
  ('Benedikt',   'boy', 'Blessed',                        'Latin'),
  ('Přemysl',    'boy', 'Thinking ahead, clever',         'Slavic'),
  ('Libor',      'boy', 'Free man',                       'Latin'),
  ('Aleš',       'boy', 'Defender of men',                'Greek'),
  ('Zbyněk',     'boy', 'Dismissing fear',                'Slavic'),
  ('Rostislav',  'boy', 'Growing glory',                  'Slavic'),
  ('Miloslav',   'boy', 'Gracious glory',                 'Slavic'),
  -- Traditional & historic Czech
  ('Václav',     'boy', 'More glory',                     'Slavic'),
  ('Vojtěch',    'boy', 'Joyful warrior',                 'Slavic'),
  ('Bořivoj',    'boy', 'Fighting warrior',               'Slavic'),
  ('Dalibor',    'boy', 'Fighting far away',              'Slavic'),
  ('Slavomír',   'boy', 'Glory and peace',                'Slavic'),
  ('Vladislav',  'boy', 'Glorious ruler',                 'Slavic'),
  ('Jaromír',    'boy', 'Spring peace',                   'Slavic'),
  ('Radimír',    'boy', 'Happy peace',                    'Slavic'),
  ('Dobroslav',  'boy', 'Good glory',                     'Slavic'),
  ('Vlastimil',  'boy', 'Gracious ruler',                 'Slavic'),
  ('Přemysl',    'boy', 'Thinking ahead',                 'Slavic'),
  ('Lumír',      'boy', 'Flowing light',                  'Slavic'),
  ('Zdeněk',     'boy', 'Follower of Saint Denis',        'Slavic'),
  ('Radek',      'boy', 'Happy, glad',                    'Slavic'),
  ('Radim',      'boy', 'Happy peace',                    'Slavic'),
  ('Ctibor',     'boy', 'Honour and battle',              'Slavic'),
  ('Ctirad',     'boy', 'Honour and counsel',             'Slavic'),
  ('Mirko',      'boy', 'Peace',                          'Slavic'),
  ('Slavko',     'boy', 'Glory',                          'Slavic'),
  ('Milán',      'boy', 'Kind, gracious',                 'Slavic'),
  ('Dušan',      'boy', 'Soul, spirit',                   'Slavic'),
  ('Branislav',  'boy', 'Glorious protector',             'Slavic'),
  ('Bronislav',  'boy', 'Armoured glory',                 'Slavic'),
  ('Prokop',     'boy', 'Progressive, advancing',         'Greek'),
  ('Metoděj',    'boy', 'Method, way',                    'Greek'),
  ('Cyril',      'boy', 'Lord, masterful',                'Greek'),
  ('Augustin',   'boy', 'Great, magnificent',             'Latin'),
  ('Maxmilián',  'boy', 'Greatest',                       'Latin'),
  ('Florián',    'boy', 'Flowering, flourishing',         'Latin'),
  ('Klement',    'boy', 'Gentle, merciful',               'Latin'),
  ('Vincenc',    'boy', 'Conquering, winning',            'Latin'),
  ('Albrecht',   'boy', 'Noble and bright',               'Germanic'),
  ('Jindřich',   'boy', 'Ruler of the home',              'Germanic'),
  ('Norbert',    'boy', 'Bright north',                   'Germanic'),
  ('Gotthard',   'boy', 'God''s strength',                'Germanic'),
  ('Luboš',      'boy', 'Dear, beloved',                  'Slavic'),
  ('Lubomír',    'boy', 'Dear peace',                     'Slavic'),
  ('Luboslav',   'boy', 'Dear glory',                     'Slavic'),
  ('Radomír',    'boy', 'Happy peace',                    'Slavic'),
  ('Slavomír',   'boy', 'Glorious peace',                 'Slavic'),
  ('Spytihněv',  'boy', 'Cunning anger',                  'Slavic'),
  ('Boleslav',   'boy', 'More glorious',                  'Slavic'),
  ('Břetislav',  'boy', 'Glorious noise',                 'Slavic'),
  ('Soběslav',   'boy', 'Glory for himself',              'Slavic'),
  ('Vratislav',  'boy', 'Return glory',                   'Slavic'),
  ('Vladivoj',   'boy', 'Ruling warrior',                 'Slavic'),
  ('Mstislav',   'boy', 'Vengeful glory',                 'Slavic'),
  ('Slavibor',   'boy', 'Glorious battle',                'Slavic'),
  ('Dobromil',   'boy', 'Good and gracious',              'Slavic'),
  ('Dobromír',   'boy', 'Good peace',                     'Slavic'),
  ('Milorad',    'boy', 'Gracious joy',                   'Slavic'),
  ('Miroslav',   'boy', 'Peace and glory',                'Slavic'),
  ('Ratibor',    'boy', 'Battle warrior',                 'Slavic'),
  ('Hostivít',   'boy', 'Guest of the tribe',             'Slavic'),
  ('Čestmír',    'boy', 'Honour and peace',               'Slavic')
ON CONFLICT (name, gender) DO NOTHING;

-- ─────────────────────────────────────────────────────────────
-- DUTCH GIRL NAMES
-- ─────────────────────────────────────────────────────────────
INSERT INTO names_db (name, gender, meaning, origin) VALUES
  -- Modern & popular
  ('Lot',        'girl', 'Veil, covering',                'Hebrew'),
  ('Isa',        'girl', 'Pledge of God',                 'Hebrew'),
  ('Maaike',     'girl', 'Beloved, bitter',               'Hebrew'),
  ('Marieke',    'girl', 'Beloved, little Mary',          'Hebrew'),
  ('Hanneke',    'girl', 'Grace, favour',                 'Hebrew'),
  ('Annelies',   'girl', 'Grace and promise of God',      'Hebrew'),
  ('Lisa',       'girl', 'My God is an oath',             'Hebrew'),
  ('Ilse',       'girl', 'Pledge of God',                 'Germanic'),
  ('Lynn',       'girl', 'Lake, waterfall',               'Welsh'),
  ('Demi',       'girl', 'Half, small, earth',            'Greek'),
  ('Hilde',      'girl', 'Battle, warrior woman',         'Germanic'),
  ('Inge',       'girl', 'Hero''s daughter',              'Norse'),
  ('Nathalie',   'girl', 'Born on Christmas Day',         'Latin'),
  ('Heleen',     'girl', 'Bright, shining light',         'Greek'),
  ('Carolien',   'girl', 'Free woman',                    'Germanic'),
  ('Miriam',     'girl', 'Beloved, wished-for',           'Hebrew'),
  ('Willeke',    'girl', 'Resolute protector',            'Germanic'),
  ('Sofie',      'girl', 'Wisdom',                        'Greek'),
  ('Zoë',        'girl', 'Life',                          'Greek'),
  ('Lieke',      'girl', 'Beloved',                       'Dutch'),
  ('Janneke',    'girl', 'God is gracious',               'Hebrew'),
  ('Grietje',    'girl', 'Pearl',                         'Greek'),
  ('Tineke',     'girl', 'Pledge of God',                 'Germanic'),
  ('Doortje',    'girl', 'Gift of God',                   'Greek'),
  ('Fien',       'girl', 'Fine, pure',                    'Dutch'),
  ('Stien',      'girl', 'Crown, wreath',                 'Greek'),
  ('Nienke',     'girl', 'Grace',                         'Frisian'),
  ('Rianne',     'girl', 'Little queen, gracious',        'Welsh'),
  ('Marleen',    'girl', 'Bitter, beloved',               'Hebrew'),
  ('Chantal',    'girl', 'Stone, rocky place',            'French'),
  ('Naomi',      'girl', 'Pleasantness',                  'Hebrew'),
  ('Fenna',      'girl', 'Peace',                         'Frisian'),
  ('Linde',      'girl', 'Linden tree, gentle',           'Germanic'),
  ('Merel',      'girl', 'Blackbird',                     'Dutch'),
  ('Sanne',      'girl', 'Lily',                          'Hebrew'),
  ('Bente',      'girl', 'Blessed',                       'Scandinavian'),
  ('Madelief',   'girl', 'Daisy flower',                  'Dutch'),
  ('Eline',      'girl', 'Light',                         'Greek'),
  ('Floor',      'girl', 'Flower, flourishing',           'Dutch'),
  ('Anouk',      'girl', 'Grace',                         'French'),
  ('Roos',       'girl', 'Rose',                          'Dutch'),
  ('Femke',      'girl', 'Peace, girl of peace',          'Frisian'),
  ('Fleur',      'girl', 'Flower',                        'French'),
  -- Traditional & regional Dutch
  ('Greet',      'girl', 'Pearl',                         'Greek'),
  ('Lies',       'girl', 'My God is an oath',             'Hebrew'),
  ('Mieke',      'girl', 'Who is like God',               'Hebrew'),
  ('Riet',       'girl', 'From the reeds',                'Dutch'),
  ('Truus',      'girl', 'Strength',                      'Germanic'),
  ('Corrie',     'girl', 'Maiden',                        'Greek'),
  ('Diny',       'girl', 'Follower of Dionysus',          'Greek'),
  ('Ans',        'girl', 'Grace',                         'Hebrew'),
  ('Nel',        'girl', 'Bright, shining',               'Greek'),
  ('Ria',        'girl', 'Bitter, beloved',               'Hebrew'),
  ('Wil',        'girl', 'Resolute protector',            'Germanic'),
  ('Ineke',      'girl', 'Pure',                          'Greek'),
  ('Anke',       'girl', 'Grace',                         'Hebrew'),
  ('Marjon',     'girl', 'Beloved',                       'Hebrew'),
  ('Corien',     'girl', 'Maiden',                        'Greek'),
  ('Rietje',     'girl', 'Little reed',                   'Dutch'),
  ('Gertruud',   'girl', 'Strong spear',                  'Germanic'),
  ('Hendrika',   'girl', 'Ruler of the home',             'Germanic'),
  ('Wilhelmina', 'girl', 'Resolute protector',            'Germanic'),
  ('Johanna',    'girl', 'God is gracious',               'Hebrew'),
  ('Petronella', 'girl', 'Rock, stone',                   'Latin'),
  ('Antoinette', 'girl', 'Priceless, praiseworthy',       'Latin'),
  ('Clasina',    'girl', 'Victory of the people',         'Greek'),
  ('Adriana',    'girl', 'From Hadria',                   'Latin'),
  ('Gesina',     'girl', 'Goose',                         'Germanic'),
  ('Trijntje',   'girl', 'Pure',                          'Greek'),
  ('Aafje',      'girl', 'Eagle',                         'Germanic'),
  ('Dirkje',     'girl', 'Ruler of the people',           'Germanic'),
  ('Grietje',    'girl', 'Pearl',                         'Greek'),
  ('Jantje',     'girl', 'God is gracious',               'Hebrew'),
  ('Maartje',    'girl', 'Of Mars, warlike',              'Latin'),
  ('Riekje',     'girl', 'Ruler of the home',             'Germanic'),
  ('Neeltje',    'girl', 'Bright, shining',               'Greek'),
  ('Pietje',     'girl', 'Rock, stone',                   'Greek'),
  ('Sijke',      'girl', 'Victory',                       'Germanic'),
  ('Akke',       'girl', 'Eagle',                         'Frisian'),
  ('Ytje',       'girl', 'Little gift',                   'Frisian'),
  ('Sjoukje',    'girl', 'Victory',                       'Frisian'),
  ('Rikst',      'girl', 'Powerful ruler',                'Frisian'),
  ('Froukje',    'girl', 'Noble, free',                   'Frisian'),
  ('Liesbeth',   'girl', 'My God is an oath',             'Hebrew'),
  ('Annemiek',   'girl', 'Grace and who is like God',     'Hebrew'),
  ('Annemarie',  'girl', 'Grace and beloved',             'Hebrew'),
  ('Mariëlle',   'girl', 'Beloved, little Mary',          'Hebrew'),
  ('Margriet',   'girl', 'Pearl',                         'Greek'),
  ('Lisette',    'girl', 'My God is an oath',             'Hebrew'),
  ('Monique',    'girl', 'Advisor',                       'Latin'),
  ('Brigitte',   'girl', 'Strength, exalted one',         'Celtic'),
  ('Claudia',    'girl', 'Lame',                          'Latin'),
  ('Pascale',    'girl', 'Easter, Passover',              'Hebrew'),
  ('Véronique',  'girl', 'True image',                    'Greek'),
  ('Elsbeth',    'girl', 'My God is an oath',             'Hebrew'),
  ('Hannelore',  'girl', 'Grace and honour',              'Germanic')
ON CONFLICT (name, gender) DO NOTHING;

-- ─────────────────────────────────────────────────────────────
-- DUTCH BOY NAMES
-- ─────────────────────────────────────────────────────────────
INSERT INTO names_db (name, gender, meaning, origin) VALUES
  -- Modern & popular
  ('Koen',       'boy', 'Brave counsel',                  'Germanic'),
  ('Sander',     'boy', 'Defender of men',                'Greek'),
  ('Pieter',     'boy', 'Rock, stone',                    'Greek'),
  ('Willem',     'boy', 'Resolute protector',             'Germanic'),
  ('Dirk',       'boy', 'Ruler of the people',            'Germanic'),
  ('Wouter',     'boy', 'Army ruler',                     'Germanic'),
  ('Matthijs',   'boy', 'Gift of God',                    'Hebrew'),
  ('Quinten',    'boy', 'Fifth',                          'Latin'),
  ('Noud',       'boy', 'Eagle power',                    'Germanic'),
  ('Pepijn',     'boy', 'Awe-inspiring',                  'Germanic'),
  ('Rens',       'boy', 'Crowned with laurel',            'Latin'),
  ('Hidde',      'boy', 'Battle, strife',                 'Frisian'),
  ('Ties',       'boy', 'Gift of God',                    'Dutch'),
  ('Bas',        'boy', 'Venerable, kingly',              'Greek'),
  ('Pim',        'boy', 'Helmet of will',                 'Germanic'),
  ('Guus',       'boy', 'Great, magnificent',             'Latin'),
  ('Joep',       'boy', 'God will add',                   'Hebrew'),
  ('Arjan',      'boy', 'Of the Adriatic',                'Latin'),
  ('Tijmen',     'boy', 'God has heard',                  'Hebrew'),
  ('Harm',       'boy', 'Army man',                       'Germanic'),
  ('Berend',     'boy', 'Brave as a bear',                'Germanic'),
  ('Gerrit',     'boy', 'Spear-brave',                    'Germanic'),
  ('Henk',       'boy', 'Ruler of the home',              'Germanic'),
  ('Reinder',    'boy', 'Wise counsellor',                'Germanic'),
  ('Ids',        'boy', 'Work, labour',                   'Frisian'),
  ('Remco',      'boy', 'Counsel power',                  'Germanic'),
  ('Joren',      'boy', 'Farmer, earth worker',           'Greek'),
  ('Tijs',       'boy', 'Gift of God',                    'Dutch'),
  ('Derk',       'boy', 'Ruler of the people',            'Germanic'),
  ('Geert',      'boy', 'Spear-brave',                    'Germanic'),
  -- Traditional & regional Dutch
  ('Hendrik',    'boy', 'Ruler of the home',              'Germanic'),
  ('Cornelis',   'boy', 'Horn, strong',                   'Latin'),
  ('Jacobus',    'boy', 'Supplanter',                     'Hebrew'),
  ('Theodorus',  'boy', 'Gift of God',                    'Greek'),
  ('Johannes',   'boy', 'God is gracious',                'Hebrew'),
  ('Adriaan',    'boy', 'From Hadria',                    'Latin'),
  ('Nicolaas',   'boy', 'Victory of the people',          'Greek'),
  ('Antonius',   'boy', 'Priceless, praiseworthy',        'Latin'),
  ('Petrus',     'boy', 'Rock, stone',                    'Greek'),
  ('Gerardus',   'boy', 'Spear-brave',                    'Germanic'),
  ('Franciscus', 'boy', 'Free man, from France',          'Latin'),
  ('Martinus',   'boy', 'Of Mars, warlike',               'Latin'),
  ('Bernardus',  'boy', 'Brave as a bear',                'Germanic'),
  ('Wilhelmus',  'boy', 'Resolute protector',             'Germanic'),
  ('Albertus',   'boy', 'Noble and bright',               'Germanic'),
  ('Hendrikus',  'boy', 'Ruler of the home',              'Germanic'),
  ('Lambertus',  'boy', 'Bright land',                    'Germanic'),
  ('Hermanus',   'boy', 'Army man',                       'Germanic'),
  ('Theodoor',   'boy', 'Gift of God',                    'Greek'),
  ('Florentijn', 'boy', 'Flourishing',                    'Latin'),
  ('Bartholomeus','boy','Son of Talmai',                  'Aramaic'),
  ('Sebastiaan', 'boy', 'Venerable, revered',             'Greek'),
  ('Christiaan', 'boy', 'Follower of Christ',             'Greek'),
  ('Michiel',    'boy', 'Who is like God',                'Hebrew'),
  ('Laurens',    'boy', 'Crowned with laurel',            'Latin'),
  ('Maarten',    'boy', 'Of Mars, warlike',               'Latin'),
  ('Jeroen',     'boy', 'Sacred name',                    'Greek'),
  ('Rutger',     'boy', 'Famous spear',                   'Germanic'),
  ('Bart',       'boy', 'Son of Talmai',                  'Aramaic'),
  ('Gijs',       'boy', 'Bright pledge',                  'Germanic'),
  ('Teun',       'boy', 'Priceless',                      'Latin'),
  ('Joop',       'boy', 'God will add',                   'Hebrew'),
  ('Wim',        'boy', 'Resolute protector',             'Germanic'),
  ('Cor',        'boy', 'Horn, strong',                   'Latin'),
  ('Arie',       'boy', 'Lion of God',                    'Hebrew'),
  ('Kees',       'boy', 'Horn, strong',                   'Latin'),
  ('Jan',        'boy', 'God is gracious',                'Hebrew'),
  ('Piet',       'boy', 'Rock, stone',                    'Greek'),
  ('Hans',       'boy', 'God is gracious',                'Hebrew'),
  ('Jaap',       'boy', 'Supplanter',                     'Hebrew'),
  ('Frits',      'boy', 'Peaceful ruler',                 'Germanic'),
  ('Roel',       'boy', 'Famous land',                    'Germanic'),
  ('Ton',        'boy', 'Priceless',                      'Latin'),
  ('Ben',        'boy', 'Son of the right hand',          'Hebrew'),
  ('Dick',       'boy', 'Ruler of the people',            'Germanic'),
  ('Boudewijn',  'boy', 'Bold friend',                    'Germanic'),
  ('Lodewijk',   'boy', 'Famous warrior',                 'Germanic'),
  ('Reinoud',    'boy', 'Counsel ruler',                  'Germanic'),
  ('Gideon',     'boy', 'Mighty warrior',                 'Hebrew'),
  ('Sjoerd',     'boy', 'Guardian',                       'Frisian'),
  ('Watze',      'boy', 'Watchful',                       'Frisian'),
  ('Wiebe',      'boy', 'Battle, strife',                 'Frisian'),
  ('Tsjebbe',    'boy', 'People',                         'Frisian'),
  ('Pier',       'boy', 'Rock, stone',                    'Frisian'),
  ('Ate',        'boy', 'Noble',                          'Frisian'),
  ('Jelle',      'boy', 'Wealthy pledge',                 'Frisian'),
  ('Douwe',      'boy', 'Dove',                           'Frisian'),
  ('Hotze',      'boy', 'Mind, spirit',                   'Frisian'),
  ('Rindert',    'boy', 'Counsel ruler',                  'Frisian')
ON CONFLICT (name, gender) DO NOTHING;

-- ─────────────────────────────────────────────────────────────
-- CZ POPULARITY — GIRLS (top 50)
-- ─────────────────────────────────────────────────────────────
WITH n AS (SELECT id, name FROM names_db WHERE gender = 'girl')
INSERT INTO name_popularity (name_id, country_code, popularity_rank, year)
SELECT n.id, p.country_code, p.rank, 2024
FROM n JOIN (VALUES
  ('Mia',        'CZ', 1),  ('Sofia',      'CZ', 2),  ('Emma',       'CZ', 3),
  ('Lucie',      'CZ', 4),  ('Anna',       'CZ', 5),  ('Tereza',     'CZ', 6),
  ('Marie',      'CZ', 7),  ('Olivia',     'CZ', 8),  ('Eva',        'CZ', 9),
  ('Natálie',    'CZ', 10), ('Eliška',     'CZ', 11), ('Karolína',   'CZ', 12),
  ('Veronika',   'CZ', 13), ('Adéla',      'CZ', 14), ('Petra',      'CZ', 15),
  ('Barbora',    'CZ', 16), ('Kateřina',   'CZ', 17), ('Kristýna',   'CZ', 18),
  ('Markéta',    'CZ', 19), ('Anežka',     'CZ', 20), ('Lenka',      'CZ', 21),
  ('Michaela',   'CZ', 22), ('Ella',       'CZ', 23), ('Zoe',        'CZ', 24),
  ('Klára',      'CZ', 25), ('Nikola',     'CZ', 26), ('Simona',     'CZ', 27),
  ('Dominika',   'CZ', 28), ('Jana',       'CZ', 29), ('Martina',    'CZ', 30),
  ('Alžběta',    'CZ', 31), ('Zuzana',     'CZ', 32), ('Amálie',     'CZ', 33),
  ('Rozálie',    'CZ', 34), ('Žofie',      'CZ', 35), ('Viktorie',   'CZ', 36),
  ('Julie',      'CZ', 37), ('Nela',       'CZ', 38), ('Ema',        'CZ', 39),
  ('Sára',       'CZ', 40), ('Linda',      'CZ', 41), ('Pavlína',    'CZ', 42),
  ('Monika',     'CZ', 43), ('Denisa',     'CZ', 44), ('Kamila',     'CZ', 45),
  ('Šárka',      'CZ', 46), ('Radka',      'CZ', 47), ('Alena',      'CZ', 48),
  ('Ivana',      'CZ', 49), ('Johana',     'CZ', 50)
) AS p(name, country_code, rank) ON n.name = p.name
ON CONFLICT (name_id, country_code) DO NOTHING;

-- ─────────────────────────────────────────────────────────────
-- CZ POPULARITY — BOYS (top 50)
-- ─────────────────────────────────────────────────────────────
WITH n AS (SELECT id, name FROM names_db WHERE gender = 'boy')
INSERT INTO name_popularity (name_id, country_code, popularity_rank, year)
SELECT n.id, p.country_code, p.rank, 2024
FROM n JOIN (VALUES
  ('Jan',        'CZ', 1),  ('Jakub',      'CZ', 2),  ('Lukáš',      'CZ', 3),
  ('Matěj',      'CZ', 4),  ('Adam',       'CZ', 5),  ('David',      'CZ', 6),
  ('Martin',     'CZ', 7),  ('Tomáš',      'CZ', 8),  ('Ondřej',     'CZ', 9),
  ('Marek',      'CZ', 10), ('Petr',       'CZ', 11), ('Jiří',       'CZ', 12),
  ('Vojtěch',    'CZ', 13), ('Václav',     'CZ', 14), ('Michal',     'CZ', 15),
  ('Radek',      'CZ', 16), ('Zdeněk',     'CZ', 17), ('Filip',      'CZ', 18),
  ('Šimon',      'CZ', 19), ('Dominik',    'CZ', 20), ('Patrik',     'CZ', 21),
  ('Pavel',      'CZ', 22), ('Josef',      'CZ', 23), ('Karel',      'CZ', 24),
  ('František',  'CZ', 25), ('Miroslav',   'CZ', 26), ('Antonín',    'CZ', 27),
  ('Matyáš',     'CZ', 28), ('Štěpán',     'CZ', 29), ('Kristián',   'CZ', 30),
  ('Kryštof',    'CZ', 31), ('Jonáš',      'CZ', 32), ('Sebastián',  'CZ', 33),
  ('Tobiáš',     'CZ', 34), ('Vít',        'CZ', 35), ('Samuel',     'CZ', 36),
  ('Ladislav',   'CZ', 37), ('Jaroslav',   'CZ', 38), ('Benedikt',   'CZ', 39),
  ('Stanislav',  'CZ', 40), ('Vladimír',   'CZ', 41), ('Oldřich',    'CZ', 42),
  ('Přemysl',    'CZ', 43), ('Libor',      'CZ', 44), ('Aleš',       'CZ', 45),
  ('Bedřich',    'CZ', 46), ('Radoslav',   'CZ', 47), ('Bohumil',    'CZ', 48),
  ('Bohdan',     'CZ', 49), ('Rostislav',  'CZ', 50)
) AS p(name, country_code, rank) ON n.name = p.name
ON CONFLICT (name_id, country_code) DO NOTHING;

-- ─────────────────────────────────────────────────────────────
-- NL POPULARITY — GIRLS (top 70)
-- ─────────────────────────────────────────────────────────────
WITH n AS (SELECT id, name FROM names_db WHERE gender = 'girl')
INSERT INTO name_popularity (name_id, country_code, popularity_rank, year)
SELECT n.id, p.country_code, p.rank, 2024
FROM n JOIN (VALUES
  ('Emma',       'NL', 1),  ('Noor',       'NL', 2),  ('Mia',        'NL', 3),
  ('Julia',      'NL', 4),  ('Sofia',      'NL', 5),  ('Olivia',     'NL', 6),
  ('Lotte',      'NL', 7),  ('Sara',       'NL', 8),  ('Anna',       'NL', 9),
  ('Fleur',      'NL', 10), ('Femke',      'NL', 11), ('Skylar',     'NL', 12),
  ('Roos',       'NL', 13), ('Floor',      'NL', 14), ('Anouk',      'NL', 15),
  ('Fenna',      'NL', 16), ('Luna',       'NL', 17), ('Bo',         'NL', 18),
  ('Lena',       'NL', 19), ('Nina',       'NL', 20), ('Iris',       'NL', 21),
  ('Elisa',      'NL', 22), ('Tess',       'NL', 23), ('Amber',      'NL', 24),
  ('Bente',      'NL', 25), ('Sanne',      'NL', 26), ('Merel',      'NL', 27),
  ('Linde',      'NL', 28), ('Eline',      'NL', 29), ('Madelief',   'NL', 30),
  ('Hannah',     'NL', 31), ('Ella',       'NL', 32), ('Charlotte',  'NL', 33),
  ('Lily',       'NL', 34), ('Manon',      'NL', 35), ('Vera',       'NL', 36),
  ('Lot',        'NL', 37), ('Isa',        'NL', 38), ('Maaike',     'NL', 39),
  ('Marieke',    'NL', 40), ('Hanneke',    'NL', 41), ('Annelies',   'NL', 42),
  ('Lisa',       'NL', 43), ('Ilse',       'NL', 44), ('Lynn',       'NL', 45),
  ('Demi',       'NL', 46), ('Hilde',      'NL', 47), ('Inge',       'NL', 48),
  ('Nathalie',   'NL', 49), ('Heleen',     'NL', 50), ('Carolien',   'NL', 51),
  ('Miriam',     'NL', 52), ('Willeke',    'NL', 53), ('Sofie',      'NL', 54),
  ('Zoë',        'NL', 55), ('Lieke',      'NL', 56), ('Janneke',    'NL', 57),
  ('Nienke',     'NL', 58), ('Rianne',     'NL', 59), ('Fien',       'NL', 60),
  ('Stien',      'NL', 61), ('Marleen',    'NL', 62), ('Naomi',      'NL', 63),
  ('Freya',      'NL', 64), ('Laura',      'NL', 65), ('Ellie',      'NL', 66),
  ('Stella',     'NL', 67), ('Grace',      'NL', 68), ('Rose',       'NL', 69),
  ('Chantal',    'NL', 70)
) AS p(name, country_code, rank) ON n.name = p.name
ON CONFLICT (name_id, country_code) DO NOTHING;

-- ─────────────────────────────────────────────────────────────
-- NL POPULARITY — BOYS (top 70)
-- ─────────────────────────────────────────────────────────────
WITH n AS (SELECT id, name FROM names_db WHERE gender = 'boy')
INSERT INTO name_popularity (name_id, country_code, popularity_rank, year)
SELECT n.id, p.country_code, p.rank, 2024
FROM n JOIN (VALUES
  ('Sem',        'NL', 1),  ('Noah',       'NL', 2),  ('Daan',       'NL', 3),
  ('Lars',       'NL', 4),  ('Liam',       'NL', 5),  ('Bram',       'NL', 6),
  ('Finn',       'NL', 7),  ('Thijs',      'NL', 8),  ('Jesse',      'NL', 9),
  ('Luuk',       'NL', 10), ('Floris',     'NL', 11), ('Stijn',      'NL', 12),
  ('Joris',      'NL', 13), ('Sven',       'NL', 14), ('Ruben',      'NL', 15),
  ('Julian',     'NL', 16), ('Thomas',     'NL', 17), ('Milan',      'NL', 18),
  ('Robin',      'NL', 19), ('Rick',       'NL', 20), ('Niels',      'NL', 21),
  ('Tom',        'NL', 22), ('Sam',        'NL', 23), ('Cas',        'NL', 24),
  ('Wout',       'NL', 25), ('Oliver',     'NL', 26), ('Jasper',     'NL', 27),
  ('Tim',        'NL', 28), ('Max',        'NL', 29), ('Lucas',      'NL', 30),
  ('Felix',      'NL', 31), ('Simon',      'NL', 32), ('Leon',       'NL', 33),
  ('Luca',       'NL', 34), ('David',      'NL', 35), ('Adam',       'NL', 36),
  ('Koen',       'NL', 37), ('Sander',     'NL', 38), ('Pieter',     'NL', 39),
  ('Willem',     'NL', 40), ('Dirk',       'NL', 41), ('Wouter',     'NL', 42),
  ('Matthijs',   'NL', 43), ('Quinten',    'NL', 44), ('Rens',       'NL', 45),
  ('Hidde',      'NL', 46), ('Bas',        'NL', 47), ('Pim',        'NL', 48),
  ('Guus',       'NL', 49), ('Joep',       'NL', 50), ('Arjan',      'NL', 51),
  ('Tijmen',     'NL', 52), ('Harm',       'NL', 53), ('Berend',     'NL', 54),
  ('Gerrit',     'NL', 55), ('Henk',       'NL', 56), ('Noud',       'NL', 57),
  ('Pepijn',     'NL', 58), ('George',     'NL', 59), ('Jack',       'NL', 60),
  ('Oscar',      'NL', 61), ('Henry',      'NL', 62), ('Leo',        'NL', 63),
  ('Benjamin',   'NL', 64), ('James',      'NL', 65), ('Elias',      'NL', 66),
  ('Jonas',      'NL', 67), ('Paul',       'NL', 68), ('Erik',       'NL', 69),
  ('Magnus',     'NL', 70)
) AS p(name, country_code, rank) ON n.name = p.name
ON CONFLICT (name_id, country_code) DO NOTHING;
