-- 006_comprehensive_cz_nl.sql
-- Full Czech and Dutch name lists sourced from behindthename.com
-- All names added with CZ/NL popularity ranks so they appear in country filter
-- Rare/traditional names get high ranks (100+) — they still appear, just sorted last
-- Safe to re-run (ON CONFLICT DO NOTHING throughout)

-- ─────────────────────────────────────────────────────────────
-- CZECH BOY NAMES (new additions)
-- ─────────────────────────────────────────────────────────────
INSERT INTO names_db (name, gender, meaning, origin) VALUES
  ('Alois',      'boy', 'Famous warrior',                 'Germanic'),
  ('Ambrož',     'boy', 'Immortal',                       'Greek'),
  ('Andrej',     'boy', 'Manly, brave',                   'Greek'),
  ('Arnošt',     'boy', 'Earnest, serious',               'Germanic'),
  ('Bartoloměj', 'boy', 'Son of Talmai',                  'Aramaic'),
  ('Blahoslav',  'boy', 'Happy glory',                    'Slavic'),
  ('Blažej',     'boy', 'Lisping, stammering',            'Latin'),
  ('Bořek',      'boy', 'Fighter',                        'Slavic'),
  ('Boris',      'boy', 'Battle glory',                   'Slavic'),
  ('Bruno',      'boy', 'Brown, armour',                  'Germanic'),
  ('Čeněk',      'boy', 'Honour and glory',               'Slavic'),
  ('Dan',        'boy', 'God is my judge',                'Hebrew'),
  ('Denis',      'boy', 'Follower of Dionysus',           'Greek'),
  ('Dezider',    'boy', 'Longed for',                     'Latin'),
  ('Drahomír',   'boy', 'Dear peace',                     'Slavic'),
  ('Drahoslav',  'boy', 'Dear glory',                     'Slavic'),
  ('Dušan',      'boy', 'Soul, spirit',                   'Slavic'),
  ('Eduard',     'boy', 'Wealthy guardian',               'English'),
  ('Edvard',     'boy', 'Wealthy guardian',               'English'),
  ('Eliáš',      'boy', 'My God is the Lord',             'Hebrew'),
  ('Emanuel',    'boy', 'God is with us',                 'Hebrew'),
  ('Emil',       'boy', 'Rival, eager',                   'Latin'),
  ('Evžen',      'boy', 'Well-born, noble',               'Greek'),
  ('Ferdinand',  'boy', 'Bold journey',                   'Germanic'),
  ('Florián',    'boy', 'Flowering, flourishing',         'Latin'),
  ('Gejza',      'boy', 'Pledge',                         'Hungarian'),
  ('Gustav',     'boy', 'Staff of the Goths',             'Germanic'),
  ('Hanuš',      'boy', 'God is gracious',                'Germanic'),
  ('Havel',      'boy', 'Rooster',                        'Czech'),
  ('Heřman',     'boy', 'Army man',                       'Germanic'),
  ('Honza',      'boy', 'God is gracious',                'Czech'),
  ('Hubert',     'boy', 'Bright heart',                   'Germanic'),
  ('Hynek',      'boy', 'Ruler of the home',              'Germanic'),
  ('Ignác',      'boy', 'Fire, fiery',                    'Latin'),
  ('Igor',       'boy', 'Warrior of peace',               'Norse'),
  ('Ilja',       'boy', 'My God is the Lord',             'Hebrew'),
  ('Jáchym',     'boy', 'Established by God',             'Hebrew'),
  ('Jákob',      'boy', 'Supplanter',                     'Hebrew'),
  ('Janek',      'boy', 'God is gracious',                'Czech'),
  ('Jára',       'boy', 'Spring, youthful',               'Czech'),
  ('Jarek',      'boy', 'Spring glory',                   'Slavic'),
  ('Jarmil',     'boy', 'Spring grace',                   'Slavic'),
  ('Jaromír',    'boy', 'Spring peace',                   'Slavic'),
  ('Jeroným',    'boy', 'Sacred name',                    'Greek'),
  ('Jindra',     'boy', 'Ruler of the home',              'Germanic'),
  ('Jindřích',   'boy', 'Ruler of the home',              'Germanic'),
  ('Juraj',      'boy', 'Farmer, earth worker',           'Greek'),
  ('Kašpar',     'boy', 'Treasurer',                      'Persian'),
  ('Kazimír',    'boy', 'Declaring peace',                'Slavic'),
  ('Klement',    'boy', 'Gentle, merciful',               'Latin'),
  ('Konrád',     'boy', 'Brave counsel',                  'Germanic'),
  ('Kvido',      'boy', 'Wide forest',                    'Germanic'),
  ('Leopold',    'boy', 'Bold people',                    'Germanic'),
  ('Luboš',      'boy', 'Dear, beloved',                  'Slavic'),
  ('Lubomír',    'boy', 'Dear peace',                     'Slavic'),
  ('Lumír',      'boy', 'Flowing light',                  'Slavic'),
  ('Maxim',      'boy', 'Greatest',                       'Latin'),
  ('Maxmilián',  'boy', 'Greatest',                       'Latin'),
  ('Mečislav',   'boy', 'Sword glory',                    'Slavic'),
  ('Metoděj',    'boy', 'Method, way',                    'Greek'),
  ('Mikoláš',    'boy', 'Victory of the people',          'Greek'),
  ('Mikuláš',    'boy', 'Victory of the people',          'Greek'),
  ('Miloš',      'boy', 'Gracious, pleasant',             'Slavic'),
  ('Mirek',      'boy', 'Peace',                          'Slavic'),
  ('Mojmír',     'boy', 'My peace',                       'Slavic'),
  ('Mstislav',   'boy', 'Vengeful glory',                 'Slavic'),
  ('Nikola',     'boy', 'Victory of the people',          'Greek'),
  ('Ota',        'boy', 'Wealth, fortune',                'Germanic'),
  ('Otakar',     'boy', 'Watchful of wealth',             'Germanic'),
  ('Otmar',      'boy', 'Famous wealth',                  'Germanic'),
  ('Oto',        'boy', 'Wealth, fortune',                'Germanic'),
  ('Otokar',     'boy', 'Watchful of wealth',             'Germanic'),
  ('Pravoslav',  'boy', 'Righteous glory',                'Slavic'),
  ('Přemek',     'boy', 'Thinking ahead',                 'Slavic'),
  ('Prokop',     'boy', 'Progressive, advancing',         'Greek'),
  ('Quido',      'boy', 'Wide forest',                    'Germanic'),
  ('Radim',      'boy', 'Happy peace',                    'Slavic'),
  ('Radko',      'boy', 'Happy, glad',                    'Slavic'),
  ('Radomil',    'boy', 'Happy grace',                    'Slavic'),
  ('Radomír',    'boy', 'Happy peace',                    'Slavic'),
  ('Radovan',    'boy', 'Happy, glad',                    'Slavic'),
  ('Radúz',      'boy', 'Happy',                          'Slavic'),
  ('Rudolf',     'boy', 'Famous wolf',                    'Germanic'),
  ('Sergej',     'boy', 'Servant',                        'Latin'),
  ('Slávek',     'boy', 'Glory',                          'Slavic'),
  ('Slavomír',   'boy', 'Glorious peace',                 'Slavic'),
  ('Soběslav',   'boy', 'Glory for himself',              'Slavic'),
  ('Svatopluk',  'boy', 'Holy people',                    'Slavic'),
  ('Svatoslav',  'boy', 'Holy glory',                     'Slavic'),
  ('Teodor',     'boy', 'Gift of God',                    'Greek'),
  ('Theodor',    'boy', 'Gift of God',                    'Greek'),
  ('Tibor',      'boy', 'From the Tiber river',           'Latin'),
  ('Urban',      'boy', 'City dweller',                   'Latin'),
  ('Valentin',   'boy', 'Strong, healthy',                'Latin'),
  ('Valentýn',   'boy', 'Strong, healthy',                'Latin'),
  ('Vašek',      'boy', 'More glory',                     'Slavic'),
  ('Vavřinec',   'boy', 'Crowned with laurel',            'Latin'),
  ('Věnceslav',  'boy', 'Crown of glory',                 'Slavic'),
  ('Vendelín',   'boy', 'Wanderer',                       'Germanic'),
  ('Věroslav',   'boy', 'Faith and glory',                'Slavic'),
  ('Viktor',     'boy', 'Conqueror, victory',             'Latin'),
  ('Vilém',      'boy', 'Resolute protector',             'Germanic'),
  ('Vincenc',    'boy', 'Conquering, winning',            'Latin'),
  ('Vítek',      'boy', 'Life, lively',                   'Latin'),
  ('Vítězslav',  'boy', 'Victory and glory',              'Slavic'),
  ('Vladan',     'boy', 'Ruling',                         'Slavic'),
  ('Vlastimír',  'boy', 'Ruling peace',                   'Slavic'),
  ('Vlastislav', 'boy', 'Ruling glory',                   'Slavic'),
  ('Vojta',      'boy', 'Joyful warrior',                 'Slavic'),
  ('Zachariáš',  'boy', 'God remembers',                  'Hebrew'),
  ('Záviš',      'boy', 'Envy',                           'Slavic'),
  ('Zbyhněv',    'boy', 'Dismissing anger',               'Slavic'),
  ('Zbyšek',     'boy', 'Dismissing',                     'Slavic'),
  ('Zdislav',    'boy', 'Glorious here',                  'Slavic'),
  ('Zikmund',    'boy', 'Victorious protection',          'Germanic'),
  ('Alexandr',   'boy', 'Defender of men',                'Greek'),
  ('Adolf',      'boy', 'Noble wolf',                     'Germanic'),
  ('Alfréd',     'boy', 'Elf counsel',                    'Germanic'),
  ('Alex',       'boy', 'Defender of men',                'Greek'),
  ('Albín',      'boy', 'White, fair',                    'Latin'),
  ('Augustin',   'boy', 'Great, magnificent',             'Latin'),
  ('Barnabáš',   'boy', 'Son of consolation',             'Aramaic'),
  ('Bernard',    'boy', 'Brave as a bear',                'Germanic'),
  ('Benjamín',   'boy', 'Son of my right hand',          'Hebrew'),
  ('Bonifác',    'boy', 'Good fate',                      'Latin'),
  ('Damián',     'boy', 'To tame, subdue',                'Greek'),
  ('Gabriel',    'boy', 'God is my strength',             'Hebrew'),
  ('Michael',    'boy', 'Who is like God',                'Hebrew')
ON CONFLICT (name, gender) DO NOTHING;

-- ─────────────────────────────────────────────────────────────
-- CZECH GIRL NAMES (new additions)
-- ─────────────────────────────────────────────────────────────
INSERT INTO names_db (name, gender, meaning, origin) VALUES
  ('Alexandra',  'girl', 'Defender of men',               'Greek'),
  ('Aloisie',    'girl', 'Famous warrior',                'Germanic'),
  ('Anastázie',  'girl', 'Resurrection',                  'Greek'),
  ('Aneta',      'girl', 'Grace',                         'Hebrew'),
  ('Andrea',     'girl', 'Manly, brave',                  'Greek'),
  ('Antonie',    'girl', 'Priceless, praiseworthy',       'Latin'),
  ('Beáta',      'girl', 'Blessed, happy',                'Latin'),
  ('Berenika',   'girl', 'Bringing victory',              'Greek'),
  ('Berta',      'girl', 'Bright, famous',                'Germanic'),
  ('Blažena',    'girl', 'Blessed',                       'Slavic'),
  ('Bohdana',    'girl', 'Gift of God',                   'Slavic'),
  ('Bohuslava',  'girl', 'Glory of God',                  'Slavic'),
  ('Bohunka',    'girl', 'Gift of God',                   'Slavic'),
  ('Boleslava',  'girl', 'More glorious',                 'Slavic'),
  ('Danuše',     'girl', 'God is my judge',               'Hebrew'),
  ('Danuška',    'girl', 'God is my judge',               'Hebrew'),
  ('Dáša',       'girl', 'Gift of God',                   'Greek'),
  ('Diana',      'girl', 'Divine, heavenly',              'Latin'),
  ('Dita',       'girl', 'Rich gift',                     'Germanic'),
  ('Dobroslava', 'girl', 'Good glory',                    'Slavic'),
  ('Dorota',     'girl', 'Gift of God',                   'Greek'),
  ('Draha',      'girl', 'Dear, precious',                'Slavic'),
  ('Drahoslava', 'girl', 'Dear glory',                    'Slavic'),
  ('Evelína',    'girl', 'Life, wished-for child',        'French'),
  ('Evženie',    'girl', 'Well-born, noble',              'Greek'),
  ('Františka',  'girl', 'Free woman, from France',       'Latin'),
  ('Gita',       'girl', 'Good, pearl',                   'Sanskrit'),
  ('Gizela',     'girl', 'Pledge',                        'Germanic'),
  ('Helena',     'girl', 'Bright, shining light',         'Greek'),
  ('Helenka',    'girl', 'Bright, shining light',         'Greek'),
  ('Helga',      'girl', 'Holy, blessed',                 'Norse'),
  ('Hermína',    'girl', 'Army man',                      'Germanic'),
  ('Hildegarda', 'girl', 'Battle guard',                  'Germanic'),
  ('Ilona',      'girl', 'Torch, bright light',           'Greek'),
  ('Ivanka',     'girl', 'God is gracious',               'Slavic'),
  ('Ivka',       'girl', 'God is gracious',               'Slavic'),
  ('Ivona',      'girl', 'Yew tree',                      'French'),
  ('Izabela',    'girl', 'My God is an oath',             'Hebrew'),
  ('Janička',    'girl', 'God is gracious',               'Czech'),
  ('Janka',      'girl', 'God is gracious',               'Czech'),
  ('Jarka',      'girl', 'Spring glory',                  'Slavic'),
  ('Jaruška',    'girl', 'Spring glory',                  'Slavic'),
  ('Jasmína',    'girl', 'Jasmine flower',                'Persian'),
  ('Jiřina',     'girl', 'Farmer, earth worker',          'Greek'),
  ('Johanka',    'girl', 'God is gracious',               'Hebrew'),
  ('Jolana',     'girl', 'Violet flower',                 'French'),
  ('Josefína',   'girl', 'God will add',                  'Hebrew'),
  ('Judita',     'girl', 'Jewish woman, praised',         'Hebrew'),
  ('Justýna',    'girl', 'Just, righteous',               'Latin'),
  ('Kája',       'girl', 'Pure',                          'Czech'),
  ('Karla',      'girl', 'Free woman',                    'Germanic'),
  ('Katka',      'girl', 'Pure',                          'Greek'),
  ('Klaudie',    'girl', 'Lame',                          'Latin'),
  ('Klotylda',   'girl', 'Famous battle',                 'Germanic'),
  ('Kornélie',   'girl', 'Horn',                          'Latin'),
  ('Kristina',   'girl', 'Follower of Christ',            'Greek'),
  ('Květa',      'girl', 'Flower, blossom',               'Czech'),
  ('Květoslava', 'girl', 'Flowering glory',               'Slavic'),
  ('Květuše',    'girl', 'Flower, blossom',               'Czech'),
  ('Ladislava',  'girl', 'Famous ruler',                  'Slavic'),
  ('Lea',        'girl', 'Weary, delicate',               'Hebrew'),
  ('Leona',      'girl', 'Lioness',                       'Latin'),
  ('Leontýna',   'girl', 'Lioness',                       'Latin'),
  ('Melánie',    'girl', 'Black, dark',                   'Greek'),
  ('Michala',    'girl', 'Who is like God',               'Hebrew'),
  ('Miloslava',  'girl', 'Gracious glory',                'Slavic'),
  ('Miluška',    'girl', 'Gracious, dear',                'Slavic'),
  ('Miriam',     'girl', 'Beloved, wished-for',           'Hebrew'),
  ('Míša',       'girl', 'Who is like God',               'Czech'),
  ('Naďa',       'girl', 'Hope',                          'Slavic'),
  ('Naděžda',    'girl', 'Hope',                          'Slavic'),
  ('Nataša',     'girl', 'Born on Christmas Day',         'Russian'),
  ('Nicol',      'girl', 'Victory of the people',         'Greek'),
  ('Nikol',      'girl', 'Victory of the people',         'Greek'),
  ('Noemi',      'girl', 'Pleasantness',                  'Hebrew'),
  ('Oldřiška',   'girl', 'Wealth and power',              'Germanic'),
  ('Olivie',     'girl', 'Olive tree',                    'Latin'),
  ('Pavla',      'girl', 'Small, humble',                 'Latin'),
  ('Petruška',   'girl', 'Rock, stone',                   'Greek'),
  ('Radana',     'girl', 'Happy',                         'Slavic'),
  ('Radomila',   'girl', 'Happy grace',                   'Slavic'),
  ('Radomíra',   'girl', 'Happy peace',                   'Slavic'),
  ('Radoslava',  'girl', 'Happy glory',                   'Slavic'),
  ('Radovana',   'girl', 'Happy',                         'Slavic'),
  ('Rebeka',     'girl', 'To bind, captivating',          'Hebrew'),
  ('Regína',     'girl', 'Queen',                         'Latin'),
  ('Renáta',     'girl', 'Reborn',                        'Latin'),
  ('Rút',        'girl', 'Friend, companion',             'Hebrew'),
  ('Sabina',     'girl', 'Sabine woman',                  'Latin'),
  ('Sandra',     'girl', 'Defender of men',               'Greek'),
  ('Šarlota',    'girl', 'Free woman',                    'French'),
  ('Silvie',     'girl', 'From the forest',               'Latin'),
  ('Šimona',     'girl', 'God has heard',                 'Hebrew'),
  ('Slávka',     'girl', 'Glory',                         'Slavic'),
  ('Stáňa',      'girl', 'Glorious government',           'Slavic'),
  ('Stela',      'girl', 'Star',                          'Latin'),
  ('Štěpánka',   'girl', 'Crown, wreath',                 'Greek'),
  ('Svatava',    'girl', 'Holy',                          'Slavic'),
  ('Svatoslava', 'girl', 'Holy glory',                    'Slavic'),
  ('Světlana',   'girl', 'Light',                         'Slavic'),
  ('Tamara',     'girl', 'Palm tree',                     'Hebrew'),
  ('Táňa',       'girl', 'Fairy queen',                   'Slavic'),
  ('Terezie',    'girl', 'To harvest',                    'Greek'),
  ('Václava',    'girl', 'More glory',                    'Slavic'),
  ('Valentýna',  'girl', 'Strong, healthy',               'Latin'),
  ('Valérie',    'girl', 'To be strong, healthy',         'Latin'),
  ('Vendula',    'girl', 'Wanderer',                      'Germanic'),
  ('Vendulka',   'girl', 'Wanderer',                      'Germanic'),
  ('Venuše',     'girl', 'Love, beauty',                  'Latin'),
  ('Věroslava',  'girl', 'Faith and glory',               'Slavic'),
  ('Vilemína',   'girl', 'Resolute protector',            'Germanic'),
  ('Vilma',      'girl', 'Resolute protector',            'Germanic'),
  ('Viola',      'girl', 'Violet flower',                 'Latin'),
  ('Vítězslava', 'girl', 'Victory and glory',             'Slavic'),
  ('Vladana',    'girl', 'Ruling',                        'Slavic'),
  ('Vladěna',    'girl', 'Ruling',                        'Slavic'),
  ('Vladimíra',  'girl', 'Great ruler',                   'Slavic'),
  ('Vladislava', 'girl', 'Glorious ruler',                'Slavic'),
  ('Vlastislava','girl', 'Ruling glory',                  'Slavic'),
  ('Vratislava', 'girl', 'Return glory',                  'Slavic'),
  ('Xenie',      'girl', 'Hospitality',                   'Greek'),
  ('Yvetta',     'girl', 'Yew tree',                      'French'),
  ('Yvona',      'girl', 'Yew tree',                      'French'),
  ('Zdislava',   'girl', 'Glorious here',                 'Slavic'),
  ('Zlatuše',    'girl', 'Golden',                        'Slavic'),
  ('Zorka',      'girl', 'Dawn',                          'Slavic'),
  ('Zuzanka',    'girl', 'Lily, graceful',                'Hebrew'),
  ('Zuzka',      'girl', 'Lily, graceful',                'Hebrew'),
  ('Jaromíra',   'girl', 'Spring peace',                  'Slavic'),
  ('Jarmila',    'girl', 'Spring grace',                  'Slavic'),
  ('Miroslava',  'girl', 'Peace and glory',               'Slavic'),
  ('Darina',     'girl', 'Gift',                          'Slavic'),
  ('Yveta',      'girl', 'Yew tree',                      'French'),
  ('Jitka',      'girl', 'Jewish woman',                  'Hebrew'),
  ('Soňa',       'girl', 'Wisdom',                        'Greek'),
  ('Taťána',     'girl', 'Fairy queen',                   'Slavic'),
  ('Apolena',    'girl', 'Of Apollo, sun',                'Greek'),
  ('Bedřiška',   'girl', 'Peaceful ruler',                'Germanic'),
  ('Danuše',     'girl', 'God is my judge',               'Hebrew'),
  ('Olívie',     'girl', 'Olive tree',                    'Latin'),
  ('Zora',       'girl', 'Dawn',                          'Slavic'),
  ('Zlata',      'girl', 'Golden',                        'Slavic'),
  ('Nora',       'girl', 'Light, honour',                 'Irish')
ON CONFLICT (name, gender) DO NOTHING;

-- ─────────────────────────────────────────────────────────────
-- DUTCH BOY NAMES (new additions)
-- ─────────────────────────────────────────────────────────────
INSERT INTO names_db (name, gender, meaning, origin) VALUES
  ('Aart',       'boy', 'Eagle power',                    'Germanic'),
  ('Abe',        'boy', 'Father of many',                 'Hebrew'),
  ('Abel',       'boy', 'Breath, vapour',                 'Hebrew'),
  ('Abraham',    'boy', 'Father of many nations',         'Hebrew'),
  ('Ad',         'boy', 'Noble',                          'Germanic'),
  ('Adelbert',   'boy', 'Noble and bright',               'Germanic'),
  ('Aldert',     'boy', 'Noble, old',                     'Germanic'),
  ('Allard',     'boy', 'Noble and brave',                'Germanic'),
  ('Alwin',      'boy', 'Wise friend',                    'Germanic'),
  ('André',      'boy', 'Manly, brave',                   'Greek'),
  ('Andries',    'boy', 'Manly, brave',                   'Greek'),
  ('Antoon',     'boy', 'Priceless',                      'Latin'),
  ('Arend',      'boy', 'Eagle power',                    'Germanic'),
  ('Aris',       'boy', 'Best',                           'Greek'),
  ('Arno',       'boy', 'Eagle power',                    'Germanic'),
  ('Arnold',     'boy', 'Eagle power',                    'Germanic'),
  ('Arnoud',     'boy', 'Eagle power',                    'Germanic'),
  ('Arnout',     'boy', 'Eagle power',                    'Germanic'),
  ('Augustijn',  'boy', 'Great, magnificent',             'Latin'),
  ('Barend',     'boy', 'Brave as a bear',                'Germanic'),
  ('Bartel',     'boy', 'Son of Talmai',                  'Aramaic'),
  ('Bastiaan',   'boy', 'Venerable, revered',             'Greek'),
  ('Boaz',       'boy', 'Swiftness, strength',            'Hebrew'),
  ('Bob',        'boy', 'Bright fame',                    'Germanic'),
  ('Boele',      'boy', 'Pledge',                         'Frisian'),
  ('Bonifaas',   'boy', 'Good fate',                      'Latin'),
  ('Bowie',      'boy', 'Blond',                          'Scottish'),
  ('Brecht',     'boy', 'Bright',                         'Germanic'),
  ('Broos',      'boy', 'Ambiguous, strength',            'Germanic'),
  ('Camiel',     'boy', 'Attendant',                      'Latin'),
  ('Carel',      'boy', 'Free man',                       'Germanic'),
  ('Casper',     'boy', 'Treasurer',                      'Persian'),
  ('Cees',       'boy', 'Horn, strong',                   'Latin'),
  ('Coenraad',   'boy', 'Brave counsel',                  'Germanic'),
  ('Constantijn','boy', 'Steadfast',                      'Latin'),
  ('Coos',       'boy', 'Horn, strong',                   'Latin'),
  ('Daley',      'boy', 'Assembly',                       'Irish'),
  ('Damiaan',    'boy', 'To tame',                        'Greek'),
  ('Diede',      'boy', 'People',                         'Germanic'),
  ('Diederick',  'boy', 'Ruler of the people',            'Germanic'),
  ('Diederik',   'boy', 'Ruler of the people',            'Germanic'),
  ('Dominicus',  'boy', 'Belonging to the Lord',          'Latin'),
  ('Dries',      'boy', 'Manly, brave',                   'Greek'),
  ('Ed',         'boy', 'Wealthy guardian',               'English'),
  ('Eddy',       'boy', 'Wealthy guardian',               'English'),
  ('Edwin',      'boy', 'Wealthy friend',                 'English'),
  ('Egbert',     'boy', 'Bright sword',                   'Germanic'),
  ('Elbert',     'boy', 'Noble and bright',               'Germanic'),
  ('Elian',      'boy', 'Sun',                            'Greek'),
  ('Emiel',      'boy', 'Rival, eager',                   'Latin'),
  ('Ernst',      'boy', 'Earnest, serious',               'Germanic'),
  ('Erwin',      'boy', 'Army friend',                    'Germanic'),
  ('Gerlof',     'boy', 'Spear wolf',                     'Germanic'),
  ('Gerolt',     'boy', 'Spear ruler',                    'Germanic'),
  ('Gijsbert',   'boy', 'Bright pledge',                  'Germanic'),
  ('Gilbert',    'boy', 'Bright pledge',                  'Germanic'),
  ('Gillis',     'boy', 'Young goat',                     'Greek'),
  ('Godfried',   'boy', 'God''s peace',                   'Germanic'),
  ('Goswin',     'boy', 'God''s friend',                  'Germanic'),
  ('Gustaaf',    'boy', 'Staff of the Goths',             'Germanic'),
  ('Han',        'boy', 'God is gracious',                'Hebrew'),
  ('Harmen',     'boy', 'Army man',                       'Germanic'),
  ('Hein',       'boy', 'Ruler of the home',              'Germanic'),
  ('Herbert',    'boy', 'Bright army',                    'Germanic'),
  ('Herman',     'boy', 'Army man',                       'Germanic'),
  ('Hieronymus', 'boy', 'Sacred name',                    'Greek'),
  ('Hilbert',    'boy', 'Battle bright',                  'Germanic'),
  ('Hubertus',   'boy', 'Bright heart',                   'Germanic'),
  ('Hubrecht',   'boy', 'Bright heart',                   'Germanic'),
  ('Huub',       'boy', 'Bright heart',                   'Germanic'),
  ('Ignaas',     'boy', 'Fire, fiery',                    'Latin'),
  ('IJsbrand',   'boy', 'Ice sword',                      'Germanic'),
  ('Ivo',        'boy', 'Yew tree',                       'Germanic'),
  ('Jaak',       'boy', 'Supplanter',                     'Hebrew'),
  ('Jelte',      'boy', 'Wealth pledge',                  'Frisian'),
  ('Jef',        'boy', 'God will add',                   'Hebrew'),
  ('Jochem',     'boy', 'Established by God',             'Hebrew'),
  ('Jodocus',    'boy', 'Lord',                           'Celtic'),
  ('Joeri',      'boy', 'Farmer, earth worker',           'Greek'),
  ('Johan',      'boy', 'God is gracious',                'Hebrew'),
  ('Joord',      'boy', 'Farmer, earth worker',           'Greek'),
  ('Joos',       'boy', 'Lord',                           'Celtic'),
  ('Jordaan',    'boy', 'To flow down',                   'Hebrew'),
  ('Jordi',      'boy', 'Farmer, earth worker',           'Greek'),
  ('Jordy',      'boy', 'Farmer, earth worker',           'Greek'),
  ('Jos',        'boy', 'God will add',                   'Hebrew'),
  ('Jozef',      'boy', 'God will add',                   'Hebrew'),
  ('Jozua',      'boy', 'God is salvation',               'Hebrew'),
  ('Judocus',    'boy', 'Lord',                           'Celtic'),
  ('Julius',     'boy', 'Youthful',                       'Latin'),
  ('Jurgen',     'boy', 'Farmer, earth worker',           'Greek'),
  ('Jurriaan',   'boy', 'Farmer, earth worker',           'Greek'),
  ('Justus',     'boy', 'Just, righteous',                'Latin'),
  ('Kai',        'boy', 'Sea',                            'Frisian'),
  ('Klaas',      'boy', 'Victory of the people',          'Greek'),
  ('Kobe',       'boy', 'Supplanter',                     'Hebrew'),
  ('Kobus',      'boy', 'Supplanter',                     'Hebrew'),
  ('Koenraad',   'boy', 'Brave counsel',                  'Germanic'),
  ('Koert',      'boy', 'Brave counsel',                  'Germanic'),
  ('Koos',       'boy', 'Supplanter',                     'Hebrew'),
  ('Kris',       'boy', 'Follower of Christ',             'Greek'),
  ('Kyan',       'boy', 'Ancient',                        'Irish'),
  ('Lambert',    'boy', 'Bright land',                    'Germanic'),
  ('Lammert',    'boy', 'Bright land',                    'Germanic'),
  ('Lau',        'boy', 'Crowned with laurel',            'Latin'),
  ('Laurentius', 'boy', 'Crowned with laurel',            'Latin'),
  ('Lex',        'boy', 'Defender of men',                'Greek'),
  ('Lieven',     'boy', 'Dear friend',                    'Germanic'),
  ('Loek',       'boy', 'Famous warrior',                 'Germanic'),
  ('Mannes',     'boy', 'God is with us',                 'Hebrew'),
  ('Marcel',     'boy', 'Of Mars, warlike',               'Latin'),
  ('Marco',      'boy', 'Of Mars, warlike',               'Latin'),
  ('Marten',     'boy', 'Of Mars, warlike',               'Latin'),
  ('Martijn',    'boy', 'Of Mars, warlike',               'Latin'),
  ('Martinus',   'boy', 'Of Mars, warlike',               'Latin'),
  ('Marvin',     'boy', 'Sea friend',                     'Welsh'),
  ('Mathijs',    'boy', 'Gift of God',                    'Hebrew'),
  ('Matthias',   'boy', 'Gift of God',                    'Hebrew'),
  ('Mees',       'boy', 'Gift of God',                    'Dutch'),
  ('Meinard',    'boy', 'Strong and brave',               'Germanic'),
  ('Meindert',   'boy', 'Strong and brave',               'Germanic'),
  ('Meine',      'boy', 'Strong and brave',               'Germanic'),
  ('Meint',      'boy', 'Strong and brave',               'Frisian'),
  ('Melchior',   'boy', 'King of light',                  'Hebrew'),
  ('Melle',      'boy', 'Work, labour',                   'Frisian'),
  ('Menno',      'boy', 'Strength',                       'Frisian'),
  ('Micha',      'boy', 'Who is like God',                'Hebrew'),
  ('Michel',     'boy', 'Who is like God',                'Hebrew'),
  ('Mick',       'boy', 'Who is like God',                'Hebrew'),
  ('Miel',       'boy', 'Who is like God',                'Dutch'),
  ('Mischa',     'boy', 'Who is like God',                'Russian'),
  ('Moos',       'boy', 'Drawn out of water',             'Hebrew'),
  ('Nick',       'boy', 'Victory of the people',          'Greek'),
  ('Nikolaas',   'boy', 'Victory of the people',          'Greek'),
  ('Niek',       'boy', 'Victory of the people',          'Dutch'),
  ('Nout',       'boy', 'Eagle power',                    'Germanic'),
  ('Olaf',       'boy', 'Ancestor''s relic',              'Norse'),
  ('Olivier',    'boy', 'Olive tree',                     'Latin'),
  ('Otto',       'boy', 'Wealth, fortune',                'Germanic'),
  ('Pascal',     'boy', 'Easter, Passover',               'Hebrew'),
  ('Pauwel',     'boy', 'Small, humble',                  'Latin'),
  ('Philip',     'boy', 'Lover of horses',                'Greek'),
  ('Quirijn',    'boy', 'Spear',                          'Latin'),
  ('Radboud',    'boy', 'Counsel bold',                   'Germanic'),
  ('Raf',        'boy', 'God has healed',                 'Hebrew'),
  ('Rafaël',     'boy', 'God has healed',                 'Hebrew'),
  ('Rein',       'boy', 'Counsel',                        'Germanic'),
  ('Reinier',    'boy', 'Wise counsellor',                'Germanic'),
  ('Reinoud',    'boy', 'Counsel ruler',                  'Germanic'),
  ('Reinout',    'boy', 'Counsel ruler',                  'Germanic'),
  ('Rembrandt',  'boy', 'Raven sword',                    'Germanic'),
  ('René',       'boy', 'Reborn',                         'Latin'),
  ('Rien',       'boy', 'Counsel',                        'Germanic'),
  ('Rinus',      'boy', 'Counsel',                        'Dutch'),
  ('Rob',        'boy', 'Bright fame',                    'Germanic'),
  ('Robbe',      'boy', 'Bright fame',                    'Germanic'),
  ('Robbert',    'boy', 'Bright fame',                    'Germanic'),
  ('Robertus',   'boy', 'Bright fame',                    'Germanic'),
  ('Robrecht',   'boy', 'Bright fame',                    'Germanic'),
  ('Rochus',     'boy', 'Rest',                           'Germanic'),
  ('Roeland',    'boy', 'Famous land',                    'Germanic'),
  ('Roelof',     'boy', 'Famous wolf',                    'Germanic'),
  ('Roger',      'boy', 'Famous spear',                   'Germanic'),
  ('Rogier',     'boy', 'Famous spear',                   'Germanic'),
  ('Rokus',      'boy', 'Rest',                           'Germanic'),
  ('Roland',     'boy', 'Famous land',                    'Germanic'),
  ('Romein',     'boy', 'From Rome',                      'Latin'),
  ('Ronald',     'boy', 'Counsel ruler',                  'Norse'),
  ('Roy',        'boy', 'King',                           'French'),
  ('Samuël',     'boy', 'Told by God',                    'Hebrew'),
  ('Senn',       'boy', 'Name of God',                    'Hebrew'),
  ('Siem',       'boy', 'God has heard',                  'Hebrew'),
  ('Siemen',     'boy', 'God has heard',                  'Hebrew'),
  ('Sieuwerd',   'boy', 'Victory guardian',               'Frisian'),
  ('Theun',      'boy', 'Gift of God',                    'Dutch'),
  ('Theunis',    'boy', 'Gift of God',                    'Dutch'),
  ('Thijmen',    'boy', 'God has heard',                  'Hebrew'),
  ('Tijn',       'boy', 'Gift of God',                    'Dutch'),
  ('Timo',       'boy', 'Honouring God',                  'Greek'),
  ('Timon',      'boy', 'Honouring',                      'Greek'),
  ('Timotheus',  'boy', 'Honouring God',                  'Greek'),
  ('Tjeerd',     'boy', 'Thor''s spear',                  'Norse'),
  ('Toon',       'boy', 'Priceless',                      'Latin'),
  ('Tuur',       'boy', 'Bear king',                      'Celtic'),
  ('Tycho',      'boy', 'Hitting the mark',               'Greek'),
  ('Tygo',       'boy', 'Hitting the mark',               'Greek'),
  ('Valentijn',  'boy', 'Strong, healthy',                'Latin'),
  ('Ward',       'boy', 'Guard, watchman',                'Germanic'),
  ('Wendel',     'boy', 'Wanderer',                       'Germanic'),
  ('Werner',     'boy', 'Army guard',                     'Germanic'),
  ('Wessel',     'boy', 'God''s pledge',                  'Germanic'),
  ('Wolter',     'boy', 'Army ruler',                     'Germanic'),
  ('Xander',     'boy', 'Defender of men',                'Greek'),
  ('Youri',      'boy', 'Farmer, earth worker',           'Greek'),
  ('Ysbrand',    'boy', 'Ice sword',                      'Germanic'),
  ('Yvo',        'boy', 'Yew tree',                       'Germanic'),
  ('Joop',       'boy', 'God will add',                   'Hebrew'),
  ('Hans',       'boy', 'God is gracious',                'Germanic'),
  ('Piet',       'boy', 'Rock, stone',                    'Greek'),
  ('Jaap',       'boy', 'Supplanter',                     'Hebrew'),
  ('Frits',      'boy', 'Peaceful ruler',                 'Germanic'),
  ('Ton',        'boy', 'Priceless',                      'Latin'),
  ('Dick',       'boy', 'Ruler of the people',            'Germanic'),
  ('Boudewijn',  'boy', 'Bold friend',                    'Germanic'),
  ('Lodewijk',   'boy', 'Famous warrior',                 'Germanic'),
  ('Gideon',     'boy', 'Mighty warrior',                 'Hebrew'),
  ('Sjoerd',     'boy', 'Guardian',                       'Frisian'),
  ('Watze',      'boy', 'Watchful',                       'Frisian'),
  ('Wiebe',      'boy', 'Battle',                         'Frisian'),
  ('Jelle',      'boy', 'Wealthy pledge',                 'Frisian'),
  ('Douwe',      'boy', 'Dove',                           'Frisian'),
  ('Ate',        'boy', 'Noble',                          'Frisian'),
  ('Ids',        'boy', 'Work, labour',                   'Frisian'),
  ('Pier',       'boy', 'Rock, stone',                    'Frisian'),
  ('Rindert',    'boy', 'Counsel ruler',                  'Frisian'),
  ('Hotze',      'boy', 'Mind, spirit',                   'Frisian'),
  ('Lieven',     'boy', 'Dear friend',                    'Germanic'),
  ('Lievin',     'boy', 'Dear friend',                    'Germanic')
ON CONFLICT (name, gender) DO NOTHING;

-- ─────────────────────────────────────────────────────────────
-- DUTCH GIRL NAMES (new additions)
-- ─────────────────────────────────────────────────────────────
INSERT INTO names_db (name, gender, meaning, origin) VALUES
  ('Ada',        'girl', 'Noble, nobility',               'Germanic'),
  ('Adelheid',   'girl', 'Noble, nobility',               'Germanic'),
  ('Adelina',    'girl', 'Noble, nobility',               'Germanic'),
  ('Agatha',     'girl', 'Good, honourable',              'Greek'),
  ('Agnes',      'girl', 'Pure, holy',                    'Greek'),
  ('Aleid',      'girl', 'Noble, nobility',               'Germanic'),
  ('Aleida',     'girl', 'Noble, nobility',               'Germanic'),
  ('Aletta',     'girl', 'Noble, nobility',               'Germanic'),
  ('Alida',      'girl', 'Noble, nobility',               'Germanic'),
  ('Alma',       'girl', 'Nourishing, kind',              'Latin'),
  ('Amalia',     'girl', 'Work, effort',                  'Germanic'),
  ('Amanda',     'girl', 'Worthy of love',                'Latin'),
  ('Angela',     'girl', 'Angel, messenger',              'Greek'),
  ('Angelien',   'girl', 'Angel, messenger',              'Greek'),
  ('Angelina',   'girl', 'Angel, messenger',              'Greek'),
  ('Angelique',  'girl', 'Angel, messenger',              'Greek'),
  ('Anika',      'girl', 'Grace',                         'Hebrew'),
  ('Anita',      'girl', 'Grace',                         'Hebrew'),
  ('Anja',       'girl', 'Grace',                         'Hebrew'),
  ('Annabel',    'girl', 'Grace and beautiful',           'Hebrew'),
  ('Anne',       'girl', 'Grace',                         'Hebrew'),
  ('Anneke',     'girl', 'Grace',                         'Hebrew'),
  ('Annelien',   'girl', 'Grace',                         'Hebrew'),
  ('Anneliese',  'girl', 'Grace and promise of God',      'Hebrew'),
  ('Annemieke',  'girl', 'Grace and who is like God',     'Hebrew'),
  ('Annet',      'girl', 'Grace',                         'Hebrew'),
  ('Annette',    'girl', 'Grace',                         'French'),
  ('Annie',      'girl', 'Grace',                         'Hebrew'),
  ('Annika',     'girl', 'Grace',                         'Hebrew'),
  ('Annuska',    'girl', 'Grace',                         'Hebrew'),
  ('Anouschka',  'girl', 'Grace',                         'Hebrew'),
  ('Anouska',    'girl', 'Grace',                         'Hebrew'),
  ('Antje',      'girl', 'Priceless',                     'Latin'),
  ('Antonia',    'girl', 'Priceless',                     'Latin'),
  ('Anuschka',   'girl', 'Grace',                         'Hebrew'),
  ('Babette',    'girl', 'Stranger, foreign',             'Greek'),
  ('Beatrix',    'girl', 'She who brings happiness',      'Latin'),
  ('Bea',        'girl', 'She who brings happiness',      'Latin'),
  ('Beau',       'girl', 'Beautiful',                     'French'),
  ('Berendina',  'girl', 'Brave as a bear',               'Germanic'),
  ('Bernadette', 'girl', 'Brave as a bear',               'Germanic'),
  ('Betje',      'girl', 'My God is an oath',             'Hebrew'),
  ('Brechtje',   'girl', 'Bright',                        'Germanic'),
  ('Brigitta',   'girl', 'Strength, exalted',             'Celtic'),
  ('Carla',      'girl', 'Free woman',                    'Germanic'),
  ('Carlijn',    'girl', 'Free woman',                    'Germanic'),
  ('Carola',     'girl', 'Free woman',                    'Germanic'),
  ('Caroline',   'girl', 'Free woman',                    'Germanic'),
  ('Catharina',  'girl', 'Pure',                          'Greek'),
  ('Cato',       'girl', 'Pure',                          'Greek'),
  ('Cecilia',    'girl', 'Blind, sixth',                  'Latin'),
  ('Charissa',   'girl', 'Grace',                         'Greek'),
  ('Christina',  'girl', 'Follower of Christ',            'Greek'),
  ('Christine',  'girl', 'Follower of Christ',            'Greek'),
  ('Cilla',      'girl', 'Who is like God',               'Dutch'),
  ('Cindy',      'girl', 'From Kynthos mountain',         'Greek'),
  ('Coba',       'girl', 'Supplanter',                    'Hebrew'),
  ('Cokkie',     'girl', 'Victory of the people',         'Dutch'),
  ('Corry',      'girl', 'Maiden',                        'Greek'),
  ('Daniëlle',   'girl', 'God is my judge',               'Hebrew'),
  ('Danielle',   'girl', 'God is my judge',               'Hebrew'),
  ('Danique',    'girl', 'God is my judge',               'Hebrew'),
  ('Daphne',     'girl', 'Laurel tree',                   'Greek'),
  ('Debora',     'girl', 'Bee',                           'Hebrew'),
  ('Denise',     'girl', 'Follower of Dionysus',          'Greek'),
  ('Désirée',    'girl', 'Longed for',                    'French'),
  ('Diantha',    'girl', 'Divine flower',                 'Greek'),
  ('Dieuwke',    'girl', 'People',                        'Frisian'),
  ('Dina',       'girl', 'Avenged',                       'Hebrew'),
  ('Dora',       'girl', 'Gift',                          'Greek'),
  ('Dorothea',   'girl', 'Gift of God',                   'Greek'),
  ('Drika',      'girl', 'Ruler of the home',             'Dutch'),
  ('Eefje',      'girl', 'Life',                          'Hebrew'),
  ('Elisabeth',  'girl', 'My God is an oath',             'Hebrew'),
  ('Elise',      'girl', 'My God is an oath',             'Hebrew'),
  ('Elke',       'girl', 'Noble, of noble kind',          'Germanic'),
  ('Ellen',      'girl', 'Bright, shining',               'Greek'),
  ('Elly',       'girl', 'Bright, shining',               'Greek'),
  ('Elma',       'girl', 'Noble protector',               'Germanic'),
  ('Els',        'girl', 'My God is an oath',             'Hebrew'),
  ('Else',       'girl', 'My God is an oath',             'Hebrew'),
  ('Elsje',      'girl', 'My God is an oath',             'Hebrew'),
  ('Elvira',     'girl', 'True, white',                   'Germanic'),
  ('Emmy',       'girl', 'Whole, universal',              'Germanic'),
  ('Erna',       'girl', 'Vigorous, capable',             'Germanic'),
  ('Gerlinde',   'girl', 'Spear, gentle',                 'Germanic'),
  ('Gertrudis',  'girl', 'Strong spear',                  'Germanic'),
  ('Gertruida',  'girl', 'Strong spear',                  'Germanic'),
  ('Greetje',    'girl', 'Pearl',                         'Greek'),
  ('Griet',      'girl', 'Pearl',                         'Greek'),
  ('Gusta',      'girl', 'Staff of the Goths',            'Germanic'),
  ('Guusje',     'girl', 'Great, magnificent',            'Latin'),
  ('Hadewych',   'girl', 'Battle strife',                 'Germanic'),
  ('Hanke',      'girl', 'Grace',                         'Hebrew'),
  ('Hanna',      'girl', 'Grace',                         'Hebrew'),
  ('Hanne',      'girl', 'Grace',                         'Hebrew'),
  ('Hannie',     'girl', 'Grace',                         'Hebrew'),
  ('Henny',      'girl', 'Ruler of the home',             'Germanic'),
  ('Henriëtte',  'girl', 'Ruler of the home',             'Germanic'),
  ('Henriette',  'girl', 'Ruler of the home',             'Germanic'),
  ('Hedwig',     'girl', 'Battle strife',                 'Germanic'),
  ('Hedy',       'girl', 'Battle strife',                 'Germanic'),
  ('Heleentje',  'girl', 'Bright, shining',               'Greek'),
  ('Helma',      'girl', 'Helmet, protection',            'Germanic'),
  ('Hendrikje',  'girl', 'Ruler of the home',             'Germanic'),
  ('Hendrina',   'girl', 'Ruler of the home',             'Germanic'),
  ('Hennie',     'girl', 'Ruler of the home',             'Germanic'),
  ('Ida',        'girl', 'Industrious, hardworking',      'Germanic'),
  ('Imke',       'girl', 'Work, labour',                  'Frisian'),
  ('Ina',        'girl', 'Pure',                          'Greek'),
  ('Indy',       'girl', 'Independent',                   'English'),
  ('Ine',        'girl', 'Pure',                          'Greek'),
  ('Ineke',      'girl', 'Pure',                          'Greek'),
  ('Inez',       'girl', 'Pure, holy',                    'Greek'),
  ('Ireen',      'girl', 'Peace',                         'Greek'),
  ('Irma',       'girl', 'Universal, whole',              'Germanic'),
  ('Isabeau',    'girl', 'My God is an oath',             'Hebrew'),
  ('Isabel',     'girl', 'My God is an oath',             'Hebrew'),
  ('Isabella',   'girl', 'My God is an oath',             'Hebrew'),
  ('Isabelle',   'girl', 'My God is an oath',             'Hebrew'),
  ('Ivonne',     'girl', 'Yew tree',                      'French'),
  ('Jacoba',     'girl', 'Supplanter',                    'Hebrew'),
  ('Jacobina',   'girl', 'Supplanter',                    'Hebrew'),
  ('Jacobine',   'girl', 'Supplanter',                    'Hebrew'),
  ('Jacomina',   'girl', 'Supplanter',                    'Hebrew'),
  ('Jana',       'girl', 'God is gracious',               'Hebrew'),
  ('Janine',     'girl', 'God is gracious',               'Hebrew'),
  ('Janna',      'girl', 'God is gracious',               'Hebrew'),
  ('Jannie',     'girl', 'God is gracious',               'Hebrew'),
  ('Jantine',    'girl', 'God is gracious',               'Dutch'),
  ('Jantje',     'girl', 'God is gracious',               'Dutch'),
  ('Jasmijn',    'girl', 'Jasmine flower',                'Persian'),
  ('Jeanette',   'girl', 'God is gracious',               'French'),
  ('Jeanine',    'girl', 'God is gracious',               'French'),
  ('Jeannette',  'girl', 'God is gracious',               'French'),
  ('Jeltje',     'girl', 'Wealth pledge',                 'Frisian'),
  ('Jennifer',   'girl', 'White wave',                    'Welsh'),
  ('Jennigje',   'girl', 'God is gracious',               'Dutch'),
  ('Jenny',      'girl', 'White wave',                    'Welsh'),
  ('Jessica',    'girl', 'God beholds',                   'Hebrew'),
  ('Jet',        'girl', 'Gift of God',                   'Dutch'),
  ('Jetta',      'girl', 'Gift of God',                   'Dutch'),
  ('Jip',        'girl', 'God is gracious',               'Dutch'),
  ('Jo',         'girl', 'God is gracious',               'Hebrew'),
  ('Jolanda',    'girl', 'Violet flower',                 'French'),
  ('Jolie',      'girl', 'Pretty',                        'French'),
  ('Joëlle',     'girl', 'God is Lord',                   'Hebrew'),
  ('Joke',       'girl', 'God is gracious',               'Dutch'),
  ('Josepha',    'girl', 'God will add',                  'Hebrew'),
  ('Josephine',  'girl', 'God will add',                  'Hebrew'),
  ('Jozefien',   'girl', 'God will add',                  'Hebrew'),
  ('Judith',     'girl', 'Jewish woman, praised',         'Hebrew'),
  ('Juliana',    'girl', 'Youthful',                      'Latin'),
  ('Juul',       'girl', 'Youthful',                      'Dutch'),
  ('Karin',      'girl', 'Pure',                          'Greek'),
  ('Karlijn',    'girl', 'Free woman',                    'Germanic'),
  ('Katinka',    'girl', 'Pure',                          'Greek'),
  ('Katja',      'girl', 'Pure',                          'Greek'),
  ('Katrien',    'girl', 'Pure',                          'Greek'),
  ('Katrijn',    'girl', 'Pure',                          'Greek'),
  ('Katelijn',   'girl', 'Pure',                          'Greek'),
  ('Katelijne',  'girl', 'Pure',                          'Greek'),
  ('Kristel',    'girl', 'Follower of Christ',            'Greek'),
  ('Kyara',      'girl', 'Dark, dark-haired',             'Irish'),
  ('Lien',       'girl', 'Bright, shining',               'Greek'),
  ('Liese',      'girl', 'My God is an oath',             'Hebrew'),
  ('Liesje',     'girl', 'My God is an oath',             'Hebrew'),
  ('Lieve',      'girl', 'Dear, beloved',                 'Germanic'),
  ('Lisanne',    'girl', 'My God is an oath, grace',      'Hebrew'),
  ('Liselot',    'girl', 'My God is an oath',             'Hebrew'),
  ('Liselotte',  'girl', 'My God is an oath',             'Hebrew'),
  ('Livia',      'girl', 'Blue, envious',                 'Latin'),
  ('Lize',       'girl', 'My God is an oath',             'Hebrew'),
  ('Loes',       'girl', 'Famous warrior',                'Germanic'),
  ('Loïs',       'girl', 'More desirable',                'Greek'),
  ('Marga',      'girl', 'Pearl',                         'Greek'),
  ('Margaretha', 'girl', 'Pearl',                         'Greek'),
  ('Margreet',   'girl', 'Pearl',                         'Greek'),
  ('Maria',      'girl', 'Beloved, wished-for',           'Hebrew'),
  ('Marianne',   'girl', 'Grace and beloved',             'Hebrew'),
  ('Mariëtte',   'girl', 'Beloved, little Mary',          'Hebrew'),
  ('Marije',     'girl', 'Beloved',                       'Hebrew'),
  ('Marijke',    'girl', 'Beloved',                       'Hebrew'),
  ('Marijse',    'girl', 'Beloved',                       'Hebrew'),
  ('Marike',     'girl', 'Beloved',                       'Hebrew'),
  ('Marina',     'girl', 'From the sea',                  'Latin'),
  ('Marion',     'girl', 'Beloved',                       'Hebrew'),
  ('Mariska',    'girl', 'Beloved',                       'Hebrew'),
  ('Marissa',    'girl', 'From the sea',                  'Latin'),
  ('Marit',      'girl', 'Pearl',                         'Greek'),
  ('Marita',     'girl', 'Pearl',                         'Greek'),
  ('Marja',      'girl', 'Beloved',                       'Hebrew'),
  ('Marjan',     'girl', 'Beloved, grace',                'Hebrew'),
  ('Marjo',      'girl', 'Beloved',                       'Hebrew'),
  ('Marjolein',  'girl', 'Marjoram, beloved',             'French'),
  ('Marjolijn',  'girl', 'Marjoram, beloved',             'French'),
  ('Mathilda',   'girl', 'Battle mighty',                 'Germanic'),
  ('Mathilde',   'girl', 'Battle mighty',                 'Germanic'),
  ('Maud',       'girl', 'Battle mighty',                 'Germanic'),
  ('Meike',      'girl', 'Who is like God',               'Hebrew'),
  ('Meintje',    'girl', 'Strong and brave',              'Frisian'),
  ('Melissa',    'girl', 'Honey bee',                     'Greek'),
  ('Mieke',      'girl', 'Who is like God',               'Hebrew'),
  ('Milou',      'girl', 'Gracious, gentle',              'French'),
  ('Mina',       'girl', 'Love',                          'Germanic'),
  ('Minke',      'girl', 'Love',                          'Frisian'),
  ('Miranda',    'girl', 'Worthy of admiration',          'Latin'),
  ('Mireille',   'girl', 'To admire',                     'Provençal'),
  ('Mirjam',     'girl', 'Beloved, wished-for',           'Hebrew'),
  ('Mirte',      'girl', 'Myrtle tree',                   'Dutch'),
  ('Mirthe',     'girl', 'Myrtle tree',                   'Dutch'),
  ('Myrthe',     'girl', 'Myrtle tree',                   'Greek'),
  ('Nadine',     'girl', 'Hope',                          'Slavic'),
  ('Natascha',   'girl', 'Born on Christmas Day',         'Russian'),
  ('Natasja',    'girl', 'Born on Christmas Day',         'Russian'),
  ('Nele',       'girl', 'Bright, shining',               'Greek'),
  ('Nes',        'girl', 'Headland',                      'Dutch'),
  ('Neske',      'girl', 'Pure, holy',                    'Dutch'),
  ('Nicole',     'girl', 'Victory of the people',         'Greek'),
  ('Nicolet',    'girl', 'Victory of the people',         'Greek'),
  ('Nicoline',   'girl', 'Victory of the people',         'Greek'),
  ('Noa',        'girl', 'Motion, movement',              'Hebrew'),
  ('Noëlle',     'girl', 'Born on Christmas Day',         'French'),
  ('Noortje',    'girl', 'Light',                         'Dutch'),
  ('Nova',       'girl', 'New',                           'Latin'),
  ('Patricia',   'girl', 'Noble, patrician',              'Latin'),
  ('Paula',      'girl', 'Small, humble',                 'Latin'),
  ('Paulien',    'girl', 'Small, humble',                 'Latin'),
  ('Rachel',     'girl', 'Ewe, gentle',                   'Hebrew'),
  ('Rebecca',    'girl', 'To bind, captivating',          'Hebrew'),
  ('Rebekka',    'girl', 'To bind, captivating',          'Hebrew'),
  ('Renate',     'girl', 'Reborn',                        'Latin'),
  ('Renée',      'girl', 'Reborn',                        'French'),
  ('Renske',     'girl', 'Counsel power',                 'Germanic'),
  ('Rika',       'girl', 'Powerful ruler',                'Germanic'),
  ('Rina',       'girl', 'Pure',                          'Greek'),
  ('Rini',       'girl', 'Powerful ruler',                'Germanic'),
  ('Roosje',     'girl', 'Rose',                          'Dutch'),
  ('Rosa',       'girl', 'Rose',                          'Latin'),
  ('Rosanne',    'girl', 'Rose and grace',                'Hebrew'),
  ('Rosemarie',  'girl', 'Rose and beloved',              'Hebrew'),
  ('Ruth',       'girl', 'Friend, companion',             'Hebrew'),
  ('Saar',       'girl', 'Princess',                      'Hebrew'),
  ('Sabien',     'girl', 'Sabine woman',                  'Latin'),
  ('Sabine',     'girl', 'Sabine woman',                  'Latin'),
  ('Sacha',      'girl', 'Defender of men',               'Greek'),
  ('Sarina',     'girl', 'Princess',                      'Hebrew'),
  ('Sascha',     'girl', 'Defender of men',               'Greek'),
  ('Saskia',     'girl', 'Saxon woman',                   'Germanic'),
  ('Selma',      'girl', 'Divine protection',             'Germanic'),
  ('Senna',      'girl', 'Name, renown',                  'Hebrew'),
  ('Silke',      'girl', 'Blind, sixth',                  'Latin'),
  ('Silvia',     'girl', 'From the forest',               'Latin'),
  ('Thirza',     'girl', 'Pleasantness',                  'Hebrew'),
  ('Tina',       'girl', 'Follower of Christ',            'Greek'),
  ('Trudie',     'girl', 'Strong spear',                  'Germanic'),
  ('Trudy',      'girl', 'Strong spear',                  'Germanic'),
  ('Ursula',     'girl', 'Little bear',                   'Latin'),
  ('Veerle',     'girl', 'Beloved',                       'Germanic'),
  ('Vesper',     'girl', 'Evening star',                  'Latin'),
  ('Willemijn',  'girl', 'Resolute protector',            'Germanic'),
  ('Willemina',  'girl', 'Resolute protector',            'Germanic'),
  ('Wilma',      'girl', 'Resolute protector',            'Germanic'),
  ('Xandra',     'girl', 'Defender of men',               'Greek'),
  ('Yfke',       'girl', 'Yew tree',                      'Frisian'),
  ('Yvonne',     'girl', 'Yew tree',                      'French')
ON CONFLICT (name, gender) DO NOTHING;

-- ─────────────────────────────────────────────────────────────
-- CZ POPULARITY — extended (ranks 51–150 for traditional/rare names)
-- These names show up in the Czech filter, sorted after the common ones
-- ─────────────────────────────────────────────────────────────
WITH n AS (SELECT id, name FROM names_db WHERE gender = 'girl')
INSERT INTO name_popularity (name_id, country_code, popularity_rank, year)
SELECT n.id, p.country_code, p.rank, 2024
FROM n JOIN (VALUES
  ('Alexandra','CZ',51),('Anastázie','CZ',52),('Aneta','CZ',53),('Andrea','CZ',54),
  ('Antonie','CZ',55),('Beáta','CZ',56),('Berenika','CZ',57),('Blanka','CZ',58),
  ('Blažena','CZ',59),('Bohdana','CZ',60),('Danuše','CZ',61),('Diana','CZ',62),
  ('Dita','CZ',63),('Dobroslava','CZ',64),('Dorota','CZ',65),('Evelína','CZ',66),
  ('Františka','CZ',67),('Gabriela','CZ',68),('Helena','CZ',69),('Ilona','CZ',70),
  ('Irena','CZ',71),('Ivana','CZ',72),('Iveta','CZ',73),('Izabela','CZ',74),
  ('Jarmila','CZ',75),('Jasmína','CZ',76),('Jiřina','CZ',77),('Johana','CZ',78),
  ('Jolana','CZ',79),('Josefína','CZ',80),('Judita','CZ',81),('Justýna','CZ',82),
  ('Kamila','CZ',83),('Karla','CZ',84),('Klaudie','CZ',85),('Kristina','CZ',86),
  ('Květa','CZ',87),('Ladislava','CZ',88),('Leona','CZ',89),('Melánie','CZ',90),
  ('Michala','CZ',91),('Milena','CZ',92),('Miloslava','CZ',93),('Miroslava','CZ',94),
  ('Naďa','CZ',95),('Naděžda','CZ',96),('Nataša','CZ',97),('Nicol','CZ',98),
  ('Nikol','CZ',99),('Noemi','CZ',100),('Olivie','CZ',101),('Pavla','CZ',102),
  ('Radana','CZ',103),('Radomíra','CZ',104),('Rebeka','CZ',105),('Regína','CZ',106),
  ('Renáta','CZ',107),('Romana','CZ',108),('Rozálie','CZ',109),('Rút','CZ',110),
  ('Sabina','CZ',111),('Sandra','CZ',112),('Silvie','CZ',113),('Šimona','CZ',114),
  ('Stela','CZ',115),('Štěpánka','CZ',116),('Svatava','CZ',117),('Světlana','CZ',118),
  ('Tamara','CZ',119),('Terezie','CZ',120),('Václava','CZ',121),('Valentýna','CZ',122),
  ('Valérie','CZ',123),('Vendula','CZ',124),('Věra','CZ',125),('Vilemína','CZ',126),
  ('Vilma','CZ',127),('Viola','CZ',128),('Vladimíra','CZ',129),('Vladislava','CZ',130),
  ('Xenie','CZ',131),('Yveta','CZ',132),('Zdena','CZ',133),('Zdeňka','CZ',134),
  ('Zdislava','CZ',135),('Zlata','CZ',136),('Zlatuše','CZ',137),('Zora','CZ',138),
  ('Zorka','CZ',139),('Žofie','CZ',140),('Ludmila','CZ',141),('Božena','CZ',142),
  ('Vlasta','CZ',143),('Libuše','CZ',144),('Milada','CZ',145),('Jaroslava','CZ',146),
  ('Stanislava','CZ',147),('Bohumila','CZ',148),('Dagmar','CZ',149),('Blažena','CZ',150)
) AS p(name, country_code, rank) ON n.name = p.name
ON CONFLICT (name_id, country_code) DO NOTHING;

WITH n AS (SELECT id, name FROM names_db WHERE gender = 'boy')
INSERT INTO name_popularity (name_id, country_code, popularity_rank, year)
SELECT n.id, p.country_code, p.rank, 2024
FROM n JOIN (VALUES
  ('Alois','CZ',51),('Ambrož','CZ',52),('Andrej','CZ',53),('Arnošt','CZ',54),
  ('Bartoloměj','CZ',55),('Blahoslav','CZ',56),('Blažej','CZ',57),('Boris','CZ',58),
  ('Bruno','CZ',59),('Čeněk','CZ',60),('Dan','CZ',61),('Denis','CZ',62),
  ('Drahomír','CZ',63),('Dušan','CZ',64),('Eduard','CZ',65),('Eliáš','CZ',66),
  ('Emanuel','CZ',67),('Emil','CZ',68),('Evžen','CZ',69),('Ferdinand','CZ',70),
  ('Gabriel','CZ',71),('Gustav','CZ',72),('Hanuš','CZ',73),('Havel','CZ',74),
  ('Heřman','CZ',75),('Honza','CZ',76),('Hubert','CZ',77),('Hynek','CZ',78),
  ('Ignác','CZ',79),('Igor','CZ',80),('Ilja','CZ',81),('Jáchym','CZ',82),
  ('Jaromír','CZ',83),('Jeroným','CZ',84),('Jindřích','CZ',85),('Juraj','CZ',86),
  ('Kašpar','CZ',87),('Kazimír','CZ',88),('Klement','CZ',89),('Konrád','CZ',90),
  ('Leopold','CZ',91),('Lumír','CZ',92),('Maxim','CZ',93),('Maxmilián','CZ',94),
  ('Metoděj','CZ',95),('Mikuláš','CZ',96),('Miloš','CZ',97),('Mirek','CZ',98),
  ('Mojmír','CZ',99),('Nikola','CZ',100),('Otakar','CZ',101),('Ota','CZ',102),
  ('Pavel','CZ',103),('Prokop','CZ',104),('Radim','CZ',105),('Radomír','CZ',106),
  ('Radovan','CZ',107),('Rudolf','CZ',108),('Slávek','CZ',109),('Slavomír','CZ',110),
  ('Svatopluk','CZ',111),('Tibor','CZ',112),('Urban','CZ',113),('Valentin','CZ',114),
  ('Vašek','CZ',115),('Vavřinec','CZ',116),('Viktor','CZ',117),('Vilém','CZ',118),
  ('Vincenc','CZ',119),('Vítězslav','CZ',120),('Vladimír','CZ',121),('Vlastimil','CZ',122),
  ('Vojta','CZ',123),('Zachariáš','CZ',124),('Zbyněk','CZ',125),('Zdeněk','CZ',126),
  ('Zikmund','CZ',127),('Bořivoj','CZ',128),('Dalibor','CZ',129),('Jaromír','CZ',130),
  ('Boleslav','CZ',131),('Břetislav','CZ',132),('Čestmír','CZ',133),('Ctibor','CZ',134),
  ('Drahoslav','CZ',135),('Horymír','CZ',136),('Lumír','CZ',137),('Radomil','CZ',138),
  ('Přemysl','CZ',139),('Soběslav','CZ',140),('Přemek','CZ',141),('Radúz','CZ',142),
  ('Svatoslav','CZ',143),('Věnceslav','CZ',144),('Vilém','CZ',145)
) AS p(name, country_code, rank) ON n.name = p.name
ON CONFLICT (name_id, country_code) DO NOTHING;

-- ─────────────────────────────────────────────────────────────
-- NL POPULARITY — extended (ranks 71–180 for traditional/rare Dutch names)
-- ─────────────────────────────────────────────────────────────
WITH n AS (SELECT id, name FROM names_db WHERE gender = 'girl')
INSERT INTO name_popularity (name_id, country_code, popularity_rank, year)
SELECT n.id, p.country_code, p.rank, 2024
FROM n JOIN (VALUES
  ('Ada','NL',71),('Adelheid','NL',72),('Agatha','NL',73),('Agnes','NL',74),
  ('Aleida','NL',75),('Aletta','NL',76),('Alma','NL',77),('Amalia','NL',78),
  ('Annabel','NL',79),('Anne','NL',80),('Anneke','NL',81),('Annelien','NL',82),
  ('Anneliese','NL',83),('Annemieke','NL',84),('Annette','NL',85),('Annika','NL',86),
  ('Antje','NL',87),('Babette','NL',88),('Beatrix','NL',89),('Brechtje','NL',90),
  ('Carla','NL',91),('Carlijn','NL',92),('Catharina','NL',93),('Cecilia','NL',94),
  ('Christina','NL',95),('Cindy','NL',96),('Daphne','NL',97),('Debora','NL',98),
  ('Denise','NL',99),('Désirée','NL',100),('Dieuwke','NL',101),('Dorothea','NL',102),
  ('Eefje','NL',103),('Elisabeth','NL',104),('Elise','NL',105),('Elke','NL',106),
  ('Ellen','NL',107),('Elvira','NL',108),('Emmy','NL',109),('Gertruida','NL',110),
  ('Guusje','NL',111),('Hadewych','NL',112),('Hanke','NL',113),('Hanna','NL',114),
  ('Hanne','NL',115),('Henriëtte','NL',116),('Ida','NL',117),('Imke','NL',118),
  ('Ineke','NL',119),('Isabeau','NL',120),('Isabel','NL',121),('Isabella','NL',122),
  ('Jacoba','NL',123),('Janneke','NL',124),('Jasmijn','NL',125),('Jeltje','NL',126),
  ('Jet','NL',127),('Jip','NL',128),('Jolanda','NL',129),('Joëlle','NL',130),
  ('Joke','NL',131),('Josephine','NL',132),('Judith','NL',133),('Juliana','NL',134),
  ('Juul','NL',135),('Karin','NL',136),('Karlijn','NL',137),('Katinka','NL',138),
  ('Katja','NL',139),('Katrien','NL',140),('Kristel','NL',141),('Lien','NL',142),
  ('Liesbeth','NL',143),('Lieve','NL',144),('Lisanne','NL',145),('Liselotte','NL',146),
  ('Loes','NL',147),('Marga','NL',148),('Margaretha','NL',149),('Maria','NL',150),
  ('Marianne','NL',151),('Mariëtte','NL',152),('Marije','NL',153),('Marijke','NL',154),
  ('Marina','NL',155),('Marjolein','NL',156),('Mathilde','NL',157),('Maud','NL',158),
  ('Melissa','NL',159),('Mieke','NL',160),('Milou','NL',161),('Minke','NL',162),
  ('Miranda','NL',163),('Mirjam','NL',164),('Mirte','NL',165),('Myrthe','NL',166),
  ('Nele','NL',167),('Nicole','NL',168),('Noa','NL',169),('Noortje','NL',170),
  ('Patricia','NL',171),('Rachel','NL',172),('Renée','NL',173),('Renske','NL',174),
  ('Roosje','NL',175),('Ruth','NL',176),('Saar','NL',177),('Saskia','NL',178),
  ('Selma','NL',179),('Silke','NL',180),('Trijntje','NL',181),('Veerle','NL',182),
  ('Wilhelmina','NL',183),('Willemijn','NL',184),('Wilma','NL',185),('Yvonne','NL',186),
  ('Grietje','NL',187),('Drika','NL',188),('Froukje','NL',189),('Sjoukje','NL',190),
  ('Yfke','NL',191),('Jantje','NL',192),('Neeltje','NL',193),('Aafje','NL',194),
  ('Dirkje','NL',195),('Maartje','NL',196),('Sijke','NL',197),('Akke','NL',198),
  ('Mirthe','NL',199),('Hanneke','NL',200)
) AS p(name, country_code, rank) ON n.name = p.name
ON CONFLICT (name_id, country_code) DO NOTHING;

WITH n AS (SELECT id, name FROM names_db WHERE gender = 'boy')
INSERT INTO name_popularity (name_id, country_code, popularity_rank, year)
SELECT n.id, p.country_code, p.rank, 2024
FROM n JOIN (VALUES
  ('Aart','NL',71),('Abe','NL',72),('Abel','NL',73),('Abraham','NL',74),
  ('Andries','NL',75),('Antoon','NL',76),('Arend','NL',77),('Arno','NL',78),
  ('Arnold','NL',79),('Arnoud','NL',80),('Arnout','NL',81),('Barend','NL',82),
  ('Bartel','NL',83),('Bastiaan','NL',84),('Boaz','NL',85),('Boele','NL',86),
  ('Boudewijn','NL',87),('Brecht','NL',88),('Carel','NL',89),('Casper','NL',90),
  ('Cees','NL',91),('Coenraad','NL',92),('Constantijn','NL',93),('Damiaan','NL',94),
  ('Diederik','NL',95),('Dries','NL',96),('Edwin','NL',97),('Egbert','NL',98),
  ('Emiel','NL',99),('Ernst','NL',100),('Erwin','NL',101),('Gerlof','NL',102),
  ('Gijsbert','NL',103),('Gillis','NL',104),('Godfried','NL',105),('Goswin','NL',106),
  ('Gustaaf','NL',107),('Han','NL',108),('Harmen','NL',109),('Herbert','NL',110),
  ('Hieronymus','NL',111),('Hubertus','NL',112),('Ivo','NL',113),('Jaap','NL',114),
  ('Jelte','NL',115),('Jochem','NL',116),('Joeri','NL',117),('Johan','NL',118),
  ('Joos','NL',119),('Jordi','NL',120),('Jos','NL',121),('Jozef','NL',122),
  ('Julius','NL',123),('Jurriaan','NL',124),('Justus','NL',125),('Klaas','NL',126),
  ('Kobe','NL',127),('Koos','NL',128),('Lambert','NL',129),('Lammert','NL',130),
  ('Lau','NL',131),('Laurentius','NL',132),('Lieven','NL',133),('Loek','NL',134),
  ('Mannes','NL',135),('Marcel','NL',136),('Marten','NL',137),('Martijn','NL',138),
  ('Mathijs','NL',139),('Matthias','NL',140),('Mees','NL',141),('Meindert','NL',142),
  ('Melchior','NL',143),('Melle','NL',144),('Menno','NL',145),('Michel','NL',146),
  ('Mischa','NL',147),('Nick','NL',148),('Nikolaas','NL',149),('Noud','NL',150),
  ('Olaf','NL',151),('Olivier','NL',152),('Otto','NL',153),('Pascal','NL',154),
  ('Philip','NL',155),('Quirijn','NL',156),('Radboud','NL',157),('Rafaël','NL',158),
  ('Reinier','NL',159),('Reinoud','NL',160),('Rembrandt','NL',161),('René','NL',162),
  ('Rien','NL',163),('Rinus','NL',164),('Robbe','NL',165),('Robbert','NL',166),
  ('Rochus','NL',167),('Roeland','NL',168),('Roelof','NL',169),('Rogier','NL',170),
  ('Rokus','NL',171),('Roland','NL',172),('Ronald','NL',173),('Roy','NL',174),
  ('Rudolf','NL',175),('Senn','NL',176),('Siem','NL',177),('Siemen','NL',178),
  ('Sieuwerd','NL',179),('Theun','NL',180),('Thijmen','NL',181),('Tijn','NL',182),
  ('Timo','NL',183),('Timon','NL',184),('Tjeerd','NL',185),('Toon','NL',186),
  ('Tuur','NL',187),('Tycho','NL',188),('Valentijn','NL',189),('Ward','NL',190),
  ('Werner','NL',191),('Wessel','NL',192),('Wolter','NL',193),('Xander','NL',194),
  ('Youri','NL',195),('Yvo','NL',196),('Joop','NL',197),('Jaap','NL',198),
  ('Jelle','NL',199),('Douwe','NL',200),('Sjoerd','NL',201),('Ate','NL',202),
  ('Ids','NL',203),('Pier','NL',204),('Wiebe','NL',205),('Hotze','NL',206),
  ('Watze','NL',207),('Frits','NL',208),('Dick','NL',209),('Lodewijk','NL',210),
  ('Boudewijn','NL',211),('Gideon','NL',212)
) AS p(name, country_code, rank) ON n.name = p.name
ON CONFLICT (name_id, country_code) DO NOTHING;
